-- Variantes de capas da DC Comics.
-- Execute depois de supabase/schema.sql no SQL Editor do Supabase.
-- Os inserts sao idempotentes e podem ser executados novamente.

-- Mantém compatibilidade com bancos que ainda tinham a validação exclusiva da DC.
alter table public.comic_cover_variants drop constraint if exists comic_cover_variants_cover_url_check;
alter table public.comic_cover_variants add constraint comic_cover_variants_cover_url_check check (
  cover_url ~ '^https://(www[.]|media[.]|i[.])?(static[.]dc[.]com|files[12][.]comics[.]org|storage[.]googleapis[.]com|dcuguide[.]com|static[.]wikia[.]nocookie[.]net|thepopverse[.]com|comicstoastonish[.]com|static[.]pulps[.]fr|sanctumsanctorumcomics[.]com|goldenapplecomics[.]com|blackdragoncomix[.]com|midtowncomics[.]com|everythingcomics[.]ca|thecomicmint[.]com|mlpnk72yciwc[.]i[.]optimole[.]com|media[.]forbiddenplanet[.]com|image[.]keycollectorcomics[.]com|comics[.]forbiddenplanet[.]co[.]uk|efantasy[.]gr|ebayimg[.]com|iwt[.]sfo2[.]cdn[.]digitaloceanspaces[.]com|shop[.]thirdeyecomics[.]com|dc[.]fandom[.]com|myshopville[.]com|cdn[.]shopify[.]com|supermanhomepage[.]com|sequentialartcomics[.]com|comickingdomcreative[.]com|img[.]hipcomic[.]com|media[.]mycomicshop[.]com|cardboardmemories[.]ca|oxfordcomicsandgames[.]com|alternateworldscomics[.]com|postimg[.]cc|imgur[.]com|ibb[.]co|comicvine[.]gamespot[.]com|zonafantasmanet[.]files[.]wordpress[.]com|stadiumcomics[.]com|cgc-emporium[.]com|marticomics[.]com|retconcomics[.]com|thecomicbookshoppe[.]com|comicsbox[.]it)/'
);
alter table public.user_cover_choices drop constraint if exists user_cover_choices_cover_url_check;
alter table public.user_cover_choices add constraint user_cover_choices_cover_url_check check (
  cover_url ~ '^https://(www[.]|media[.]|i[.])?(static[.]dc[.]com|files[12][.]comics[.]org|storage[.]googleapis[.]com|dcuguide[.]com|static[.]wikia[.]nocookie[.]net|thepopverse[.]com|comicstoastonish[.]com|static[.]pulps[.]fr|sanctumsanctorumcomics[.]com|goldenapplecomics[.]com|blackdragoncomix[.]com|midtowncomics[.]com|everythingcomics[.]ca|thecomicmint[.]com|mlpnk72yciwc[.]i[.]optimole[.]com|media[.]forbiddenplanet[.]com|image[.]keycollectorcomics[.]com|comics[.]forbiddenplanet[.]co[.]uk|efantasy[.]gr|ebayimg[.]com|iwt[.]sfo2[.]cdn[.]digitaloceanspaces[.]com|shop[.]thirdeyecomics[.]com|dc[.]fandom[.]com|myshopville[.]com|cdn[.]shopify[.]com|supermanhomepage[.]com|sequentialartcomics[.]com|comickingdomcreative[.]com|img[.]hipcomic[.]com|media[.]mycomicshop[.]com|cardboardmemories[.]ca|oxfordcomicsandgames[.]com|alternateworldscomics[.]com|postimg[.]cc|imgur[.]com|ibb[.]co|comicvine[.]gamespot[.]com|zonafantasmanet[.]files[.]wordpress[.]com|stadiumcomics[.]com|cgc-emporium[.]com|marticomics[.]com|retconcomics[.]com|thecomicbookshoppe[.]com|comicsbox[.]it)/'
);

-- Remove a capa de referência redundante que é igual à capa principal.
delete from public.comic_cover_variants
where item_id = 'shadow-war-2022-001'
  and variant_key = 'reference-cover';

-- Corrige os IDs antigos da Guerra pela Terra-3 para o formato usado pelo catálogo.
delete from public.comic_cover_variants
where (item_id = 'war-earth-3-2022-001' and variant_key in ('reference-cover', 'gleb-melnikov', 'liam-sharp', 'guillem-march'))
   or (item_id = 'war-earth-3-2022-002' and variant_key = 'gleb-melnikov');

-- Remove IDs antigos das séries recentes antes de inserir os IDs alinhados ao catálogo.
delete from public.comic_cover_variants
where item_id in (
  'dark-crisis-2022-001', 'dc-ko-2025-001', 'challengers-unknown-2025-001',
  'one-star-squadron-2022-001', 'shadow-war-2022-001', 'shadow-war-2022-002',
  'shadow-war-2022-003', 'shadow-war-2022-009', 'absolute-power-2024-001',
  'atom-project-2025-001', 'fire-ice-smallville-2023-001', 'flash-fastest-2022-001',
  'green-lantern-2021-001', 'green-lantern-2023-001', 'green-lantern-war-journal-2023-001',
  'justice-godzilla-kong-2023-001', 'justice-league-unlimited-2025-001', 'justice-society-2023-001',
  'knight-terrors-2023-001', 'lazarus-planet-2023-001', 'monkey-prince-2022-001',
  'new-gods-2025-001', 'next-batman-second-son-2021-001', 'nubia-amazons-2021-001',
  'penguin-2023-001', 'poison-ivy-2022-001', 'power-girl-special-2023-001',
  'question-watchtower-2024-001', 'robin-2021-001', 'shazam-2021-001', 'shazam-2023-001',
  'stargirl-lost-children-2022-001', 'superboy-tomorrow-2023-001', 'superman-2023-001',
  'superman-kal-el-returns-2022-001', 'superman-lost-2023-001', 'superman-son-kal-el-2021-001',
  'swamp-thing-2021-001', 'titans-2023-001', 'trial-amazons-2022-001', 'we-are-yesterday-2025-001',
  'wildcats-2023-001', 'wonder-girl-2021-001', 'wonder-woman-2023-001'
);

insert into public.comic_cover_variants (item_id, variant_key, label, cover_url, source_url)
values
  ('absolute-batman-001', 'jim-lee', 'Jim Lee', 'https://static.dc.com/2024-08/ABS_BM_CV1_JIM-LEE-VARIANT.jpg', 'https://www.dc.com/blog/2024/08/22/new-absolute-dc-cover-art-and-logos-are-revealed'),
  ('absolute-batman-001', 'mitch-gerads', 'Mitch Gerads', 'https://static.dc.com/2024-08/ABSOLUTE-BATMAN-Cv1-OTO-variant-Mitch-Gerads.jpg', 'https://www.dc.com/blog/2024/08/22/new-absolute-dc-cover-art-and-logos-are-revealed'),
  ('absolute-batman-001', 'wes-craig', 'Wes Craig e Mike Spicer', 'https://static.dc.com/2024-08/ABSOLUTE-BATMAN-Cv1-OTO-variant-Wes-Craig.jpg', 'https://www.dc.com/blog/2024/08/22/new-absolute-dc-cover-art-and-logos-are-revealed'),
  ('absolute-batman-001', 'ian-bertram', 'Ian Bertram', 'https://static.dc.com/2024-08/ABSOLUTE-BATMAN-Cv1-1_25-variant-Ian-Bertram.jpg', 'https://www.dc.com/blog/2024/08/22/new-absolute-dc-cover-art-and-logos-are-revealed'),
  ('absolute-batman-006', 'frank-quitely', 'Frank Quitely', 'https://static.dc.com/2024-12/AB06_Cvr_Var_Frank%20Quitely.jpeg', 'https://www.dc.com/blog/2024/12/17/absolute-batman-6-batman-s-showdown-against-black-mask-and-his-party-animals-arrives-this-march'),
  ('absolute-batman-006', 'simon-bisley', 'Simon Bisley', 'https://static.dc.com/2024-12/ABM06_Cvr_Var_Simon%20Bisley.jpeg', 'https://www.dc.com/blog/2024/12/17/absolute-batman-6-batman-s-showdown-against-black-mask-and-his-party-animals-arrives-this-march'),
  ('absolute-batman-006', 'john-mccrea', 'John McCrea', 'https://static.dc.com/2024-12/ABM06_Cvr_Var_John%20McCrea.jpeg', 'https://www.dc.com/blog/2024/12/17/absolute-batman-6-batman-s-showdown-against-black-mask-and-his-party-animals-arrives-this-march'),
  ('absolute-batman-006', 'alex-maleev', 'Alex Maleev', 'https://static.dc.com/2024-12/ABM06_Cvr_Var_Alex%20Maleev.jpg', 'https://www.dc.com/blog/2024/12/17/absolute-batman-6-batman-s-showdown-against-black-mask-and-his-party-animals-arrives-this-march'),
  ('absolute-superman-001', 'jim-lee', 'Jim Lee, Scott Williams e Alex Sinclair', 'https://static.dc.com/2024-10/ABSM01_Cvr_Var_Jim%20Lee.jpg', 'https://www.dc.com/blog/2024/10/11/dc-preview-absolute-superman-1-jason-aaron-and-rafa-sandoval-complete-the-trinity-of-dc-s-absolute-universe-this-november'),
  ('absolute-superman-001', 'jim-lee-bw', 'Jim Lee, Scott Williams e Alex Sinclair - preto e branco', 'https://static.dc.com/2024-10/ABSM01_Cvr_Var_Lee%20BW.jpg', 'https://www.dc.com/blog/2024/10/11/dc-preview-absolute-superman-1-jason-aaron-and-rafa-sandoval-complete-the-trinity-of-dc-s-absolute-universe-this-november'),
  ('absolute-superman-001', 'wes-craig', 'Wes Craig e Mike Spicer', 'https://static.dc.com/2024-10/ABSM01_Cvr_Var_Wes%20Craig.jpg', 'https://www.dc.com/blog/2024/10/11/dc-preview-absolute-superman-1-jason-aaron-and-rafa-sandoval-complete-the-trinity-of-dc-s-absolute-universe-this-november'),
  ('absolute-superman-001', 'matteo-scalera', 'Matteo Scalera', 'https://static.dc.com/2024-10/ABSM01_Cvr_Var_Matteo%20Scalera.jpg', 'https://www.dc.com/blog/2024/10/11/dc-preview-absolute-superman-1-jason-aaron-and-rafa-sandoval-complete-the-trinity-of-dc-s-absolute-universe-this-november'),
  ('absolute-superman-001', 'clayton-crain', 'Clayton Crain', 'https://static.dc.com/2024-10/ABSM01_Cvr_Var_Clayton%20Crain.jpg', 'https://www.dc.com/blog/2024/10/11/dc-preview-absolute-superman-1-jason-aaron-and-rafa-sandoval-complete-the-trinity-of-dc-s-absolute-universe-this-november'),
  ('absolute-superman-001', 'foil-logo', 'Variante foil do simbolo S', 'https://static.dc.com/2024-10/ABSM01_Cvr_Var_Foil_Logo.jpg', 'https://www.dc.com/blog/2024/10/11/dc-preview-absolute-superman-1-jason-aaron-and-rafa-sandoval-complete-the-trinity-of-dc-s-absolute-universe-this-november'),
  ('absolute-batman-003', 'stevan-subic', 'Stevan Subić', 'https://www.midtowncomics.com/images/PRODUCT/XL/2375252_xl.jpg', 'https://www.midtowncomics.com/product/2375252'),
  ('absolute-batman-004', 'james-harren', 'James Harren', 'https://www.midtowncomics.com/images/PRODUCT/XL/2382487_xl.jpg', 'https://www.midtowncomics.com/product/2382487'),
  ('absolute-batman-005', 'joelle-jones', 'Joëlle Jones', 'https://thecomicmint.com/cdn/shop/files/STL357798_1024x.jpg?v=1742471433', 'https://thecomicmint.com/products/absolute-batman-5-joelle-jones-cover-b'),
  ('absolute-batman-005', 'ian-bertram', 'Ian Bertram', 'https://mlpnk72yciwc.i.optimole.com/cqhiHLc.IIZS~2ef73/w%3Aauto/h%3Aauto/q%3A75/https%3A/bleedingcool.com/wp-content/uploads/2025/02/1224DC010.jpg', 'https://bleedingcool.com/comics/absolute-batman-5-preview-black-mask-tests-bruces-breaking-point/'),
  ('absolute-batman-005', 'clay-mann-seth-mann', 'Clay Mann e Seth Mann', 'https://media.forbiddenplanet.com/products/c2/11/11bbe67fd134452d59ef864aab934a797546.jpg', 'https://forbiddenplanet.com/444144-absolute-batman-5-cover-f-clay-mann-seth-mann-card-stock-variant/'),
  ('absolute-superman-002', 'rafael-albuquerque', 'Rafael Albuquerque', 'https://image.keycollectorcomics.com/media/b016221b-f5c6-4d13-8bd3-6a337e104ff9.jpg', 'https://www.keycollectorcomics.com/issue/absolute-superman-1-2%2C834412/'),
  ('absolute-superman-004', 'keron-grant', 'Keron Grant', 'https://comics.forbiddenplanet.co.uk/cdn/shop/files/202411-0000479182.jpg?v=1738758369', 'https://comics.forbiddenplanet.co.uk/products/1224dc022-absolute-superman-4'),
  ('black-adam-justice-society-files-002', 'photo-cyclone', 'Variante fotográfica - Cyclone / Quintessa Swindell', 'https://storage.googleapis.com/hipcomic/p/8c5589abb52a30ce10db9bfe1181bfba.jpg', 'https://www.hipcomic.com/listing/black-adam-justice-society-files-cyclone-1-cvr-b-photo-variant-dc-2022-nm/10181647'),
  ('black-adam-justice-society-files-003', 'photo-atom-smasher', 'Variante fotográfica - Atom Smasher / Noah Centineo', 'https://media.thepopverse.com/media/ba_jsf_atom-smasher-photo-variant-cover-a2hjq2lmvivfrmtuju4fk1lyda.jpg', 'https://www.thepopverse.com/justice-society-black-adam-comic'),
  ('black-adam-justice-society-files-004', 'photo-doctor-fate', 'Variante fotográfica - Dr. Fate / Pierce Brosnan', 'https://static.dc.com/dc/files/default_images/BA_JSF_Dr%2520Fate%2520%2528photo%2520variant%2520cover%2529_62a0e574532ec1.12474987.jpg', 'https://www.dc.com/blog/2022/06/09/new-cover-art-for-black-adam-the-justice-society-files-one-shots'),
  ('flashpoint-beyond-000', 'eduardo-risso', 'Eduardo Risso', 'https://dcuguide.com/images/3/3d/Flashpoint_Beyond_0_%28Cover_B%29.png', 'https://dcuguide.com/Flashpoint_Beyond_0'),
  ('flashpoint-beyond-000', 'max-dunbar', 'Max Dunbar - variante 1:25', 'https://dcuguide.com/images/f/fc/Flashpoint_Beyond_0_%28Cover_C%29.png', 'https://dcuguide.com/Flashpoint_Beyond_0'),
  ('flashpoint-beyond-001', 'xermanico', 'Xermanico', 'https://dcuguide.com/images/1/18/Flashpoint_Beyond_1_%28Cover_B%29.png', 'https://dcuguide.com/Flashpoint_Beyond_1'),
  ('flashpoint-beyond-001', 'nick-bradshaw', 'Nick Bradshaw - variante 1:25', 'https://dcuguide.com/images/c/ce/Flashpoint_Beyond_1_%28Cover_C%29.png', 'https://dcuguide.com/Flashpoint_Beyond_1'),
  ('flashpoint-beyond-001', 'todd-nauck', 'Todd Nauck - variante 1:50', 'https://dcuguide.com/images/b/b2/Flashpoint_Beyond_1_%28Cover_D%29.png', 'https://dcuguide.com/Flashpoint_Beyond_1'),
  ('flashpoint-beyond-002', 'xermanico', 'Xermanico', 'https://dcuguide.com/images/3/38/Flashpoint_Beyond_2_%28Cover_B%29.png', 'https://dcuguide.com/Flashpoint_Beyond_2'),
  ('flashpoint-beyond-002', 'jason-fabok', 'Jason Fabok - variante 1:25', 'https://dcuguide.com/images/f/ff/Flashpoint_Beyond_2_%28Cover_C%29.png', 'https://dcuguide.com/Flashpoint_Beyond_2'),
  ('flashpoint-beyond-002', 'ivan-reis', 'Ivan Reis - variante 1:50 da História da DC', 'https://dcuguide.com/images/b/b8/Flashpoint_Beyond_2_%28Cover_D%29.png', 'https://dcuguide.com/Flashpoint_Beyond_2'),
  ('aquaman-the-becoming-001', 'khary-randolph', 'Khary Randolph', 'https://dcuguide.com/images/3/37/Aquaman_-_The_Becoming_1_%28Cover_B%29.png', 'https://dcuguide.com/Aquaman%3A_The_Becoming_1'),
  ('aquaman-the-becoming-001', 'francis-manapul', 'Francis Manapul - variante 1:25', 'https://dcuguide.com/images/b/b1/Aquaman_-_The_Becoming_1_%28Cover_C%29.png', 'https://dcuguide.com/Aquaman%3A_The_Becoming_1'),
  ('aquaman-the-becoming-002', 'khary-randolph', 'Khary Randolph', 'https://dcuguide.com/images/e/ed/Aquaman_-_The_Becoming_2_%28Cover_B%29.png', 'https://dcuguide.com/Aquaman%3A_The_Becoming_2'),
  ('aquaman-the-becoming-003', 'khary-randolph', 'Khary Randolph', 'https://dcuguide.com/images/6/6f/Aquaman_-_The_Becoming_3_%28Cover_B%29.png', 'https://dcuguide.com/Aquaman%3A_The_Becoming_3'),
  ('aquaman-the-becoming-004', 'khary-randolph', 'Khary Randolph', 'https://dcuguide.com/images/7/7c/Aquaman_-_The_Becoming_4_%28Cover_B%29.png', 'https://dcuguide.com/Aquaman%3A_The_Becoming_4'),
  ('aquaman-the-becoming-005', 'khary-randolph', 'Khary Randolph', 'https://dcuguide.com/images/0/01/Aquaman_-_The_Becoming_5_%28Cover_B%29.png', 'https://dcuguide.com/Aquaman%3A_The_Becoming_5'),
  ('aquaman-the-becoming-006', 'khary-randolph', 'Khary Randolph', 'https://dcuguide.com/images/d/d9/Aquaman_-_The_Becoming_6_%28Cover_B%29.png', 'https://dcuguide.com/Aquaman%3A_The_Becoming_6'),
  ('harley-quinn-2021-001', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/8/89/Harley_Quinn_Vol._4_1_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_1'),
  ('harley-quinn-2021-001', 'yoshitaka-amano', 'Yoshitaka Amano', 'https://dcuguide.com/images/4/40/Harley_Quinn_Vol._4_1_%28Cover_D%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_1'),
  ('harley-quinn-2021-002', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/7/73/Harley_Quinn_Vol._4_2_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_2'),
  ('harley-quinn-2021-003', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/e/ef/Harley_Quinn_Vol._4_3_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_3'),
  ('harley-quinn-2021-004', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/3/35/Harley_Quinn_Vol._4_4_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_4'),
  ('harley-quinn-2021-004', 'kris-anka', 'Kris Anka - DC Pride', 'https://dcuguide.com/images/f/f6/Harley_Quinn_Vol._4_4_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_4'),
  ('harley-quinn-2021-005', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/f/fe/Harley_Quinn_Vol._4_5_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_5'),
  ('harley-quinn-2021-006', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/7/70/Harley_Quinn_Vol._4_6_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_6'),
  ('harley-quinn-2021-006', 'riccardo-federici', 'Riccardo Federici', 'https://dcuguide.com/images/1/11/Harley_Quinn_Vol._4_6_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_6'),
  ('harley-quinn-2021-007', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/9/9c/Harley_Quinn_Vol._4_7_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_7'),
  ('harley-quinn-2021-008', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/5/5a/Harley_Quinn_Vol._4_8_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_8'),
  ('harley-quinn-2021-009', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/9/9e/Harley_Quinn_Vol._4_9_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_9'),
  ('harley-quinn-2021-010', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/0/0f/Harley_Quinn_Vol._4_10_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_10'),
  ('harley-quinn-2021-010', 'rachta-lin', 'Rachta Lin - variante 1:25', 'https://dcuguide.com/images/a/ae/Harley_Quinn_Vol._4_10_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_10'),
  ('harley-quinn-2021-011', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/c/c3/Harley_Quinn_Vol._4_11_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_11'),
  ('harley-quinn-2021-011', 'acky-bright', 'Acky Bright', 'https://dcuguide.com/images/3/37/Harley_Quinn_Vol._4_11_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_11'),
  ('harley-quinn-2021-011', 'dima-ivanov', 'Dima Ivanov - variante Peacemaker', 'https://dcuguide.com/images/8/8b/Harley_Quinn_Vol._4_11_%28Cover_D%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_11'),
  ('harley-quinn-2021-012', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/e/ec/Harley_Quinn_Vol._4_12_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_12'),
  ('harley-quinn-2021-012', 'rian-gonzales', 'Rian Gonzales - variante 1:25', 'https://dcuguide.com/images/4/4d/Harley_Quinn_Vol._4_12_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_12'),
  ('harley-quinn-2021-013', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/4/43/Harley_Quinn_Vol._4_13_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_13'),
  ('harley-quinn-2021-013', 'mico-suayan', 'Mico Suayan - variante 1:25', 'https://dcuguide.com/images/3/3e/Harley_Quinn_Vol._4_13_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_13'),
  ('harley-quinn-2021-013', 'simone-bianchi', 'Simone Bianchi - variante do filme The Batman', 'https://dcuguide.com/images/2/28/Harley_Quinn_Vol._4_13_%28Cover_D%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_13'),
  ('harley-quinn-2021-014', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/a/a3/Harley_Quinn_Vol._4_14_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_14'),
  ('harley-quinn-2021-014', 'bengal', 'Bengal - variante 1:25', 'https://dcuguide.com/images/f/fb/Harley_Quinn_Vol._4_14_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_14'),
  ('harley-quinn-2021-015', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/9/96/Harley_Quinn_Vol._4_15_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_15'),
  ('harley-quinn-2021-015', 'kamome-shirahama', 'Kamome Shirahama - variante 1:25', 'https://dcuguide.com/images/1/10/Harley_Quinn_Vol._4_15_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_15'),
  ('harley-quinn-2021-016', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/2/25/Harley_Quinn_Vol._4_16_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_16'),
  ('harley-quinn-2021-016', 'ivan-tao', 'Ivan Tao - variante 1:25', 'https://dcuguide.com/images/a/a2/Harley_Quinn_Vol._4_16_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_16'),
  ('harley-quinn-2021-016', 'olivier-coipel', 'Olivier Coipel - variante DC Pride', 'https://dcuguide.com/images/3/38/Harley_Quinn_Vol._4_16_%28Cover_D%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_16'),
  ('harley-quinn-2021-017', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/a/a7/Harley_Quinn_Vol._4_17_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_17'),
  ('harley-quinn-2021-017', 'leirix', 'Leirix - variante 1:25', 'https://dcuguide.com/images/2/2e/Harley_Quinn_Vol._4_17_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_17'),
  ('harley-quinn-2021-018', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/7/73/Harley_Quinn_Vol._4_18_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_18'),
  ('harley-quinn-2021-018', 'rose-besch', 'Rose Besch - variante 1:25', 'https://dcuguide.com/images/a/af/Harley_Quinn_Vol._4_18_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_18'),
  ('harley-quinn-2021-018', 'ryan-sook-batman-1', 'Ryan Sook - homenagem a Batman #1', 'https://dcuguide.com/images/d/d5/Harley_Quinn_Vol._4_18_%28Cover_D%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_18'),
  ('harley-quinn-2021-019', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/a/a5/Harley_Quinn_Vol._4_19_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_19'),
  ('harley-quinn-2021-019', 'jimbobox', 'Jimbobox - variante 1:25', 'https://dcuguide.com/images/6/6a/Harley_Quinn_Vol._4_19_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_19'),
  ('harley-quinn-2021-019', 'ryan-sook-detective-38', 'Ryan Sook - homenagem a Detective Comics #38', 'https://dcuguide.com/images/0/0f/Harley_Quinn_Vol._4_19_%28Cover_D%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_19'),
  ('harley-quinn-2021-020', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/e/ef/Harley_Quinn_Vol._4_20_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_20'),
  ('harley-quinn-2021-020', 'jay-anacleto', 'Jay Anacleto - variante 1:25', 'https://dcuguide.com/images/2/27/Harley_Quinn_Vol._4_20_%28Cover_C%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_20'),
  ('harley-quinn-2021-020', 'ryan-sook-detective-359', 'Ryan Sook - homenagem a Detective Comics #359', 'https://dcuguide.com/images/7/74/Harley_Quinn_Vol._4_20_%28Cover_D%29.png', 'https://dcuguide.com/Harley_Quinn_Vol._4_20'),
  ('harley-quinn-2021-annual', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/d/db/Harley_Quinn_2021_Annual_1_%28Cover_B%29.png', 'https://dcuguide.com/Harley_Quinn_2021_Annual_1'),
  ('black-manta-2021-001', 'sanford-greene', 'Sanford Greene', 'https://dcuguide.com/images/4/42/Black_Manta_1_%28Cover_B%29.png', 'https://dcuguide.com/Black_Manta_1'),
  ('black-manta-2021-001', 'francis-manapul', 'Francis Manapul - variante conectada', 'https://dcuguide.com/images/f/f2/Black_Manta_1_%28Cover_C%29.png', 'https://dcuguide.com/Black_Manta_1'),
  ('black-manta-2021-002', 'sanford-greene', 'Sanford Greene', 'https://dcuguide.com/images/6/69/Black_Manta_2_%28Cover_B%29.png', 'https://dcuguide.com/Black_Manta_2'),
  ('black-manta-2021-003', 'sanford-greene', 'Sanford Greene', 'https://dcuguide.com/images/6/60/Black_Manta_3_%28Cover_B%29.png', 'https://dcuguide.com/Black_Manta_3'),
  ('black-manta-2021-004', 'sanford-greene', 'Sanford Greene', 'https://dcuguide.com/images/b/bb/Black_Manta_4_%28Cover_B%29.png', 'https://dcuguide.com/Black_Manta_4'),
  ('black-manta-2021-005', 'sanford-greene', 'Sanford Greene', 'https://dcuguide.com/images/7/79/Black_Manta_5_%28Cover_B%29.png', 'https://dcuguide.com/Black_Manta_5'),
  ('black-manta-2021-006', 'sanford-greene', 'Sanford Greene', 'https://dcuguide.com/images/9/98/Black_Manta_6_%28Cover_B%29.png', 'https://dcuguide.com/Black_Manta_6'),
  ('adventures-superman-jon-kent-001', 'zu-orzu', 'Zu Orzu', 'https://dcuguide.com/images/7/7b/Adventures_of_Superman_-_Jon_Kent_1_%28Cover_B%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_1'),
  ('adventures-superman-jon-kent-001', 'rafael-sarmento', 'Rafael Sarmento', 'https://dcuguide.com/images/2/26/Adventures_of_Superman_-_Jon_Kent_1_%28Cover_C%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_1'),
  ('adventures-superman-jon-kent-001', 'yasmin-flores-montanez', 'Yasmin Flores Montanez', 'https://dcuguide.com/images/6/6a/Adventures_of_Superman_-_Jon_Kent_1_%28Cover_D%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_1'),
  ('adventures-superman-jon-kent-001', 'al-kaplan', 'A.L. Kaplan', 'https://dcuguide.com/images/6/6d/Adventures_of_Superman_-_Jon_Kent_1_%28Cover_E%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_1'),
  ('adventures-superman-jon-kent-001', 'clayton-henry', 'Clayton Henry - variante foil 1:50', 'https://dcuguide.com/images/9/90/Adventures_of_Superman_-_Jon_Kent_1_%28Cover_F%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_1'),
  ('adventures-superman-jon-kent-001', 'megan-huang', 'Megan Huang', 'https://dcuguide.com/images/a/ab/Adventures_of_Superman_-_Jon_Kent_1_%28Cover_G%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_1'),
  ('adventures-superman-jon-kent-001', 'jordi-tarragona', 'Jordi Tarragona - variante 1:25', 'https://dcuguide.com/images/f/ff/Adventures_of_Superman_-_Jon_Kent_1_%28Cover_H%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_1'),
  ('adventures-superman-jon-kent-001', 'clayton-henry-foil', 'Clayton Henry - variante foil 1:50', 'https://dcuguide.com/images/4/45/Adventures_of_Superman_-_Jon_Kent_1_%28Cover_I%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_1'),
  ('adventures-superman-jon-kent-001', 'dan-mora', 'Dan Mora - variante de design 1:100', 'https://dcuguide.com/images/8/84/Adventures_of_Superman_-_Jon_Kent_1_%28Cover_J%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_1'),
  ('adventures-superman-jon-kent-001', 'lee-weeks', 'Lee Weeks - variante do filme Shazam!', 'https://dcuguide.com/images/0/01/Adventures_of_Superman_-_Jon_Kent_1_%28Cover_K%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_1'),
  ('adventures-superman-jon-kent-002', 'zu-orzu', 'Zu Orzu', 'https://dcuguide.com/images/3/38/Adventures_of_Superman_-_Jon_Kent_2_%28Cover_B%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_2'),
  ('adventures-superman-jon-kent-002', 'tiago-da-silva', 'Tiago da Silva', 'https://dcuguide.com/images/e/ea/Adventures_of_Superman_-_Jon_Kent_2_%28Cover_C%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_2'),
  ('adventures-superman-jon-kent-002', 'mike-perkins', 'Mike Perkins - variante 1:25', 'https://dcuguide.com/images/8/87/Adventures_of_Superman_-_Jon_Kent_2_%28Cover_D%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_2'),
  ('adventures-superman-jon-kent-002', 'clayton-henry-foil', 'Clayton Henry - variante foil 1:50', 'https://dcuguide.com/images/a/ad/Adventures_of_Superman_-_Jon_Kent_2_%28Cover_E%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_2'),
  ('adventures-superman-jon-kent-002', 'john-timms', 'John Timms', 'https://dcuguide.com/images/a/af/Adventures_of_Superman_-_Jon_Kent_2_%28Cover_F%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_2'),
  ('adventures-superman-jon-kent-003', 'zu-orzu', 'Zu Orzu', 'https://dcuguide.com/images/e/ea/Adventures_of_Superman_-_Jon_Kent_3_%28Cover_B%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_3'),
  ('adventures-superman-jon-kent-003', 'afua-richardson', 'Afua Richardson', 'https://dcuguide.com/images/7/7c/Adventures_of_Superman_-_Jon_Kent_3_%28Cover_C%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_3'),
  ('adventures-superman-jon-kent-003', 'travis-mercer', 'Travis Mercer - variante 1:25', 'https://dcuguide.com/images/6/6e/Adventures_of_Superman_-_Jon_Kent_3_%28Cover_D%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_3'),
  ('adventures-superman-jon-kent-003', 'clayton-henry-foil', 'Clayton Henry - variante foil 1:50', 'https://dcuguide.com/images/c/c6/Adventures_of_Superman_-_Jon_Kent_3_%28Cover_E%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_3'),
  ('adventures-superman-jon-kent-004', 'zu-orzu', 'Zu Orzu', 'https://dcuguide.com/images/2/2f/Adventures_of_Superman_-_Jon_Kent_4_%28Cover_B%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_4'),
  ('adventures-superman-jon-kent-004', 'al-barrionuevo', 'Al Barrionuevo', 'https://dcuguide.com/images/c/c9/Adventures_of_Superman_-_Jon_Kent_4_%28Cover_C%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_4'),
  ('adventures-superman-jon-kent-004', 'tyler-kirkham', 'Tyler Kirkham - variante 1:25', 'https://dcuguide.com/images/3/34/Adventures_of_Superman_-_Jon_Kent_4_%28Cover_D%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_4'),
  ('adventures-superman-jon-kent-004', 'clayton-henry-foil', 'Clayton Henry - variante foil 1:50', 'https://dcuguide.com/images/8/8b/Adventures_of_Superman_-_Jon_Kent_4_%28Cover_E%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_4'),
  ('adventures-superman-jon-kent-004', 'stephen-byrne', 'Stephen Byrne - variante DC Pride', 'https://dcuguide.com/images/a/ac/Adventures_of_Superman_-_Jon_Kent_4_%28Cover_F%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_4'),
  ('adventures-superman-jon-kent-005', 'jim-cheung', 'Jim Cheung e Jay David Ramos', 'https://dcuguide.com/images/4/4e/Adventures_of_Superman_-_Jon_Kent_5_%28Cover_B%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_5'),
  ('adventures-superman-jon-kent-005', 'hayden-sherman', 'Hayden Sherman', 'https://dcuguide.com/images/0/09/Adventures_of_Superman_-_Jon_Kent_5_%28Cover_C%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_5'),
  ('adventures-superman-jon-kent-005', 'zu-orzu', 'Zu Orzu - variante 1:25', 'https://dcuguide.com/images/6/6c/Adventures_of_Superman_-_Jon_Kent_5_%28Cover_D%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_5'),
  ('adventures-superman-jon-kent-005', 'clayton-henry-foil', 'Clayton Henry - variante foil 1:50', 'https://dcuguide.com/images/d/d6/Adventures_of_Superman_-_Jon_Kent_5_%28Cover_E%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_5'),
  ('adventures-superman-jon-kent-006', 'ariel-colon', 'Ariel Colón', 'https://dcuguide.com/images/f/f0/Adventures_of_Superman_-_Jon_Kent_6_%28Cover_B%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_6'),
  ('adventures-superman-jon-kent-006', 'laura-braga', 'Laura Braga', 'https://dcuguide.com/images/8/80/Adventures_of_Superman_-_Jon_Kent_6_%28Cover_C%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_6'),
  ('adventures-superman-jon-kent-006', 'zu-orzu', 'Zu Orzu - variante 1:25', 'https://dcuguide.com/images/e/ee/Adventures_of_Superman_-_Jon_Kent_6_%28Cover_D%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_6'),
  ('adventures-superman-jon-kent-006', 'clayton-henry-foil', 'Clayton Henry - variante foil 1:50', 'https://dcuguide.com/images/5/51/Adventures_of_Superman_-_Jon_Kent_6_%28Cover_E%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_6'),
  ('adventures-superman-jon-kent-006', 'cully-hamner', 'Cully Hamner - variante do filme Besouro Azul', 'https://dcuguide.com/images/9/99/Adventures_of_Superman_-_Jon_Kent_6_%28Cover_F%29.png', 'https://dcuguide.com/Adventures_of_Superman%3A_Jon_Kent_6'),
  ('green-arrow-2023-001', 'frank-cho', 'Frank Cho e Sabine Rich', 'https://dcuguide.com/images/d/d0/Green_Arrow_Vol._8_1_%28Cover_B%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_1'),
  ('green-arrow-2023-001', 'david-nakayama', 'David Nakayama', 'https://dcuguide.com/images/4/47/Green_Arrow_Vol._8_1_%28Cover_C%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_1'),
  ('green-arrow-2023-001', 'ejikure', 'Ejikure - variante 1:25', 'https://dcuguide.com/images/2/2f/Green_Arrow_Vol._8_1_%28Cover_D%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_1'),
  ('green-arrow-2023-001', 'frank-cho-foil', 'Frank Cho e Sabine Rich - variante foil 1:50', 'https://dcuguide.com/images/0/07/Green_Arrow_Vol._8_1_%28Cover_E%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_1'),
  ('green-arrow-2023-001', 'blank', 'Variante em branco', 'https://dcuguide.com/images/0/0a/Green_Arrow_Vol._8_1_%28Cover_F%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_1'),
  ('green-arrow-2023-001', 'sean-izaakse-foil', 'Sean Izaakse - variante foil wraparound', 'https://dcuguide.com/images/8/88/Green_Arrow_Vol._8_1_%28Cover_G%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_1'),
  ('green-arrow-2023-002', 'david-nakayama', 'David Nakayama', 'https://dcuguide.com/images/b/b5/Green_Arrow_Vol._8_2_%28Cover_B%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_2'),
  ('green-arrow-2023-002', 'ejikure', 'Ejikure - variante 1:25', 'https://dcuguide.com/images/a/ab/Green_Arrow_Vol._8_2_%28Cover_C%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_2'),
  ('green-arrow-2023-002', 'marcio-takara', 'Marcio Takara - variante AAPI Heritage Month', 'https://dcuguide.com/images/8/87/Green_Arrow_Vol._8_2_%28Cover_D%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_2'),
  ('green-arrow-2023-002', 'sean-izaakse-design', 'Sean Izaakse - variante de design', 'https://dcuguide.com/images/7/70/Green_Arrow_Vol._8_2_%28Cover_E%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_2'),
  ('green-arrow-2023-003', 'derrick-chew', 'Derrick Chew', 'https://dcuguide.com/images/5/5f/Green_Arrow_Vol._8_3_%28Cover_B%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_3'),
  ('green-arrow-2023-003', 'ejikure', 'Ejikure - variante 1:25', 'https://dcuguide.com/images/2/2f/Green_Arrow_Vol._8_3_%28Cover_C%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_3'),
  ('green-arrow-2023-003', 'luciano-vecchio', 'Luciano Vecchio - variante DC Pride', 'https://dcuguide.com/images/1/11/Green_Arrow_Vol._8_3_%28Cover_D%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_3'),
  ('green-arrow-2023-004', 'kendrick-lim', 'Kendrick Lim - variante card stock', 'https://dcuguide.com/images/9/91/Green_Arrow_Vol._8_4_%28Cover_B%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_4'),
  ('green-arrow-2023-004', 'james-stokoe', 'James Stokoe - variante 1:25 card stock', 'https://dcuguide.com/images/f/f6/Green_Arrow_Vol._8_4_%28Cover_C%29.png', 'https://dcuguide.com/Green_Arrow_Vol._8_4'),
  ('birds-of-prey-2023-001', 'artgerm', 'Artgerm', 'https://dcuguide.com/images/d/d7/Birds_of_Prey_Vol._5_1_%28Cover_B%29.png', 'https://dcuguide.com/Birds_of_Prey_Vol._5_1'),
  ('birds-of-prey-2023-001', 'chris-bachalo', 'Chris Bachalo e Jaime Mendoza', 'https://dcuguide.com/images/1/1c/Birds_of_Prey_Vol._5_1_%28Cover_C%29.png', 'https://dcuguide.com/Birds_of_Prey_Vol._5_1'),
  ('birds-of-prey-2023-001', 'blank', 'Variante em branco card stock', 'https://dcuguide.com/images/3/3f/Birds_of_Prey_Vol._5_1_%28Cover_D%29.png', 'https://dcuguide.com/Birds_of_Prey_Vol._5_1'),
  ('birds-of-prey-2023-001', 'nick-bradshaw', 'Nick Bradshaw', 'https://dcuguide.com/images/4/4f/Birds_of_Prey_Vol._5_1_%28Cover_E%29.png', 'https://dcuguide.com/Birds_of_Prey_Vol._5_1'),
  ('birds-of-prey-2023-001', 'chris-bachalo-bw', 'Chris Bachalo e Jaime Mendoza - preto e branco', 'https://dcuguide.com/images/9/97/Birds_of_Prey_Vol._5_1_%28Cover_F%29.png', 'https://dcuguide.com/Birds_of_Prey_Vol._5_1'),
  ('birds-of-prey-2023-001', 'leonardo-romero', 'Leonardo Romero e Jordie Bellaire', 'https://dcuguide.com/images/4/4d/Birds_of_Prey_Vol._5_1_%28Cover_G%29.png', 'https://dcuguide.com/Birds_of_Prey_Vol._5_1'),
  ('birds-of-prey-2023-001', 'frank-cho-triptych', 'Frank Cho e Sabine Rich - variante triptych gatefold', 'https://dcuguide.com/images/d/d5/Birds_of_Prey_Vol._5_1_%28Cover_H%29.png', 'https://dcuguide.com/Birds_of_Prey_Vol._5_1'),
  ('batgirls-2022-001', 'inhyuk-lee-masked', 'InHyuk Lee - versão mascarada', 'https://dcuguide.com/images/3/35/Batgirls_1_%28Cover_B%29.png', 'https://dcuguide.com/Batgirls_1'),
  ('batgirls-2022-001', 'rian-gonzales', 'Rian Gonzales - variante 1:25', 'https://dcuguide.com/images/4/49/Batgirls_1_%28Cover_C%29.png', 'https://dcuguide.com/Batgirls_1'),
  ('batgirls-2022-001', 'yoshitaka-amano', 'Yoshitaka Amano - variante de equipe', 'https://dcuguide.com/images/5/5d/Batgirls_1_%28Cover_D%29.png', 'https://dcuguide.com/Batgirls_1'),
  ('batgirls-2022-001', 'inhyuk-lee-unmasked', 'InHyuk Lee - versão sem máscara', 'https://dcuguide.com/images/8/81/Batgirls_1_%28Cover_E%29.png', 'https://dcuguide.com/Batgirls_1'),
  ('batgirls-2022-001', 'dan-hipp', 'Dan Hipp - variante 1:50', 'https://dcuguide.com/images/e/ea/Batgirls_1_%28Cover_F%29.png', 'https://dcuguide.com/Batgirls_1'),
  ('batgirls-2022-002', 'hicham-hibachi', 'Hicham Hibachi', 'https://dcuguide.com/images/3/3f/Batgirls_2_%28Cover_B%29.png', 'https://dcuguide.com/Batgirls_2'),
  ('batgirls-2022-002', 'rian-gonzales', 'Rian Gonzales - variante 1:25', 'https://dcuguide.com/images/9/9d/Batgirls_2_%28Cover_C%29.png', 'https://dcuguide.com/Batgirls_2'),
  ('batgirls-2022-003', 'kim-jacinto', 'Kim Jacinto', 'https://dcuguide.com/images/1/1c/Batgirls_3_%28Cover_B%29.png', 'https://dcuguide.com/Batgirls_3'),
  ('batgirls-2022-003', 'rian-gonzales', 'Rian Gonzales - variante 1:25', 'https://dcuguide.com/images/1/12/Batgirls_3_%28Cover_C%29.png', 'https://dcuguide.com/Batgirls_3'),
  ('batgirls-2022-004', 'michael-cho', 'Michael Cho', 'https://dcuguide.com/images/5/5d/Batgirls_4_%28Cover_B%29.png', 'https://dcuguide.com/Batgirls_4'),
  ('batgirls-2022-004', 'rian-gonzales', 'Rian Gonzales - variante 1:25', 'https://dcuguide.com/images/a/a4/Batgirls_4_%28Cover_C%29.png', 'https://dcuguide.com/Batgirls_4'),
  ('batgirls-2022-004', 'jonboy-meyers', 'Jonboy Meyers - variante do filme Batman', 'https://dcuguide.com/images/0/09/Batgirls_4_%28Cover_D%29.png', 'https://dcuguide.com/Batgirls_4'),
  ('batgirls-2022-004', 'paulina-ganucheau', 'Paulina Ganucheau - variante do Dia Internacional da Mulher', 'https://dcuguide.com/images/f/f1/Batgirls_4_%28Cover_E%29.png', 'https://dcuguide.com/Batgirls_4'),
  ('batgirls-2022-005', 'michael-cho', 'Michael Cho', 'https://dcuguide.com/images/c/c9/Batgirls_5_%28Cover_B%29.png', 'https://dcuguide.com/Batgirls_5'),
  ('batgirls-2022-005', 'rian-gonzales', 'Rian Gonzales - variante 1:25', 'https://dcuguide.com/images/7/71/Batgirls_5_%28Cover_C%29.png', 'https://dcuguide.com/Batgirls_5'),
  ('batgirls-2022-006', 'michael-cho', 'Michael Cho', 'https://dcuguide.com/images/4/41/Batgirls_6_%28Cover_B%29.png', 'https://dcuguide.com/Batgirls_6'),
  ('batgirls-2022-006', 'rian-gonzales', 'Rian Gonzales - variante 1:25', 'https://dcuguide.com/images/3/39/Batgirls_6_%28Cover_C%29.png', 'https://dcuguide.com/Batgirls_6'),
  ('batgirls-2022-006', 'audrey-mok', 'Audrey Mok - variante AAPI Heritage Month', 'https://dcuguide.com/images/b/bf/Batgirls_6_%28Cover_D%29.png', 'https://dcuguide.com/Batgirls_6'),
  ('batgirls-2022-007', 'kim-jacinto', 'Kim Jacinto', 'https://dcuguide.com/images/b/b4/Batgirls_7_%28Cover_B%29.png', 'https://dcuguide.com/Batgirls_7'),
  ('batgirls-2022-007', 'rian-gonzales', 'Rian Gonzales - variante 1:25', 'https://dcuguide.com/images/9/94/Batgirls_7_%28Cover_C%29.png', 'https://dcuguide.com/Batgirls_7'),
  ('batman-beyond-neo-year-2022-001', 'christian-ward', 'Christian Ward', 'https://dcuguide.com/images/c/cc/Batman_Beyond_-_Neo-Year_1_%28Cover_B%29.png', 'https://dcuguide.com/Batman_Beyond%3A_Neo-Year_1'),
  ('batman-beyond-neo-year-2022-001', 'simone-di-meo', 'Simone Di Meo - variante 1:25', 'https://dcuguide.com/images/1/1e/Batman_Beyond_-_Neo-Year_1_%28Cover_C%29.png', 'https://dcuguide.com/Batman_Beyond%3A_Neo-Year_1'),
  ('batman-beyond-neo-year-2022-001', 'jim-cheung', 'Jim Cheung - variante 1:100', 'https://dcuguide.com/images/a/ac/Batman_Beyond_-_Neo-Year_1_%28Cover_D%29.png', 'https://dcuguide.com/Batman_Beyond%3A_Neo-Year_1'),
  ('batman-beyond-neo-year-2022-002', 'christian-ward', 'Christian Ward', 'https://dcuguide.com/images/d/d7/Batman_Beyond_-_Neo-Year_2_%28Cover_B%29.png', 'https://dcuguide.com/Batman_Beyond%3A_Neo-Year_2'),
  ('batman-beyond-neo-year-2022-003', 'christian-ward', 'Christian Ward', 'https://dcuguide.com/images/c/c2/Batman_Beyond_-_Neo-Year_3_%28Cover_B%29.png', 'https://dcuguide.com/Batman_Beyond%3A_Neo-Year_3'),
  ('batman-beyond-neo-year-2022-004', 'christian-ward', 'Christian Ward', 'https://dcuguide.com/images/d/de/Batman_Beyond_-_Neo-Year_4_%28Cover_B%29.png', 'https://dcuguide.com/Batman_Beyond%3A_Neo-Year_4'),
  ('batman-beyond-neo-year-2022-005', 'christian-ward', 'Christian Ward', 'https://dcuguide.com/images/b/ba/Batman_Beyond_-_Neo-Year_5_%28Cover_B%29.png', 'https://dcuguide.com/Batman_Beyond%3A_Neo-Year_5'),
  ('batman-beyond-neo-year-2022-006', 'christian-ward', 'Christian Ward', 'https://dcuguide.com/images/7/7b/Batman_Beyond_-_Neo-Year_6_%28Cover_B%29.png', 'https://dcuguide.com/Batman_Beyond%3A_Neo-Year_6'),
  ('batman-beyond-neo-year-2022-006', 'max-dunbar', 'Max Dunbar', 'https://dcuguide.com/images/4/43/Batman_Beyond_-_Neo-Year_6_%28Cover_C%29.png', 'https://dcuguide.com/Batman_Beyond%3A_Neo-Year_6'),
  ('batman-vs-robin-2022-001', 'joshua-middleton', 'Joshua Middleton', 'https://dcuguide.com/images/d/d6/Batman_vs._Robin_1_%28Cover_B%29.png', 'https://dcuguide.com/Batman_vs._Robin_1'),
  ('batman-vs-robin-2022-001', 'alexander-lozano', 'Alexander Lozano', 'https://dcuguide.com/images/3/38/Batman_vs._Robin_1_%28Cover_C%29.png', 'https://dcuguide.com/Batman_vs._Robin_1'),
  ('batman-vs-robin-2022-001', 'jason-fabok', 'Jason Fabok', 'https://dcuguide.com/images/b/be/Batman_vs._Robin_1_%28Cover_D%29.png', 'https://dcuguide.com/Batman_vs._Robin_1'),
  ('batman-vs-robin-2022-001', 'lucio-parrillo', 'Lucio Parrillo - variante 1:25', 'https://dcuguide.com/images/5/51/Batman_vs._Robin_1_%28Cover_E%29.png', 'https://dcuguide.com/Batman_vs._Robin_1'),
  ('batman-vs-robin-2022-001', 'bryan-hitch', 'Bryan Hitch - variante 1:50', 'https://dcuguide.com/images/6/68/Batman_vs._Robin_1_%28Cover_F%29.png', 'https://dcuguide.com/Batman_vs._Robin_1'),
  ('batman-vs-robin-2022-001', 'mahmud-asrar-foil', 'Mahmud Asrar - variante foil', 'https://dcuguide.com/images/e/ed/Batman_vs._Robin_1_%28Cover_G%29.png', 'https://dcuguide.com/Batman_vs._Robin_1'),
  ('batman-vs-robin-2022-001', 'dave-rapoza', 'Dave Rapoza - variante de equipe', 'https://dcuguide.com/images/7/77/Batman_vs._Robin_1_%28Cover_H%29.png', 'https://dcuguide.com/Batman_vs._Robin_1'),
  ('batman-vs-robin-2022-001', 'blank', 'Variante em branco', 'https://dcuguide.com/images/f/f2/Batman_vs._Robin_1_%28Cover_I%29.png', 'https://dcuguide.com/Batman_vs._Robin_1'),
  ('batman-vs-robin-2022-001', 'steve-beach', 'Steve Beach', 'https://dcuguide.com/images/d/db/Batman_vs._Robin_1_%28Cover_J%29.png', 'https://dcuguide.com/Batman_vs._Robin_1'),
  ('batman-vs-robin-2022-001', 'francis-manapul', 'Francis Manapul', 'https://dcuguide.com/images/0/00/Batman_vs._Robin_1_%28Cover_K%29.png', 'https://dcuguide.com/Batman_vs._Robin_1'),
  ('batman-vs-robin-2022-002', 'greg-capullo', 'Greg Capullo e Jonathan Glapion', 'https://dcuguide.com/images/d/db/Batman_vs._Robin_2_%28Cover_B%29.png', 'https://dcuguide.com/Batman_vs._Robin_2'),
  ('batman-vs-robin-2022-002', 'rafael-sarmento', 'Rafael Sarmento - variante 1:25', 'https://dcuguide.com/images/1/15/Batman_vs._Robin_2_%28Cover_C%29.png', 'https://dcuguide.com/Batman_vs._Robin_2'),
  ('batman-vs-robin-2022-002', 'clayton-henry', 'Clayton Henry - variante 1:50', 'https://dcuguide.com/images/e/ed/Batman_vs._Robin_2_%28Cover_D%29.png', 'https://dcuguide.com/Batman_vs._Robin_2'),
  ('batman-vs-robin-2022-002', 'francis-manapul', 'Francis Manapul', 'https://dcuguide.com/images/e/e1/Batman_vs._Robin_2_%28Cover_E%29.png', 'https://dcuguide.com/Batman_vs._Robin_2'),
  ('batman-vs-robin-2022-003', 'alex-maleev', 'Alex Maleev', 'https://dcuguide.com/images/9/9d/Batman_vs._Robin_3_%28Cover_B%29.png', 'https://dcuguide.com/Batman_vs._Robin_3'),
  ('batman-vs-robin-2022-003', 'mario-foccillo', 'Mario Foccillo - variante 1:25', 'https://dcuguide.com/images/a/a0/Batman_vs._Robin_3_%28Cover_C%29.png', 'https://dcuguide.com/Batman_vs._Robin_3'),
  ('batman-vs-robin-2022-003', 'tony-s-daniel', 'Tony S. Daniel - variante 1:50', 'https://dcuguide.com/images/4/43/Batman_vs._Robin_3_%28Cover_D%29.png', 'https://dcuguide.com/Batman_vs._Robin_3'),
  ('batman-vs-robin-2022-003', 'carlo-barberi', 'Carlo Barberi - variante ''90s Rewind', 'https://dcuguide.com/images/5/58/Batman_vs._Robin_3_%28Cover_E%29.png', 'https://dcuguide.com/Batman_vs._Robin_3'),
  ('batman-vs-robin-2022-003', 'mateus-manhanini', 'Mateus Manhanini', 'https://dcuguide.com/images/2/2c/Batman_vs._Robin_3_%28Cover_F%29.png', 'https://dcuguide.com/Batman_vs._Robin_3'),
  ('batman-vs-robin-2022-003', 'mario-foccillo-g', 'Mario Foccillo', 'https://dcuguide.com/images/9/98/Batman_vs._Robin_3_%28Cover_G%29.png', 'https://dcuguide.com/Batman_vs._Robin_3'),
  ('batman-vs-robin-2022-003', 'mario-foccillo-h', 'Mario Foccillo', 'https://dcuguide.com/images/e/e0/Batman_vs._Robin_3_%28Cover_H%29.png', 'https://dcuguide.com/Batman_vs._Robin_3'),
  ('batman-vs-robin-2022-003', 'mario-foccillo-i', 'Mario Foccillo', 'https://dcuguide.com/images/8/81/Batman_vs._Robin_3_%28Cover_I%29.png', 'https://dcuguide.com/Batman_vs._Robin_3'),
  ('batman-vs-robin-2022-003', 'mario-foccillo-j', 'Mario Foccillo', 'https://dcuguide.com/images/2/2b/Batman_vs._Robin_3_%28Cover_J%29.png', 'https://dcuguide.com/Batman_vs._Robin_3'),
  ('batman-vs-robin-2022-004', 'simone-di-meo', 'Simone Di Meo', 'https://dcuguide.com/images/a/ab/Batman_vs._Robin_4_%28Cover_B%29.png', 'https://dcuguide.com/Batman_vs._Robin_4'),
  ('batman-vs-robin-2022-004', 'john-giang', 'John Giang - variante 1:25', 'https://dcuguide.com/images/7/76/Batman_vs._Robin_4_%28Cover_C%29.png', 'https://dcuguide.com/Batman_vs._Robin_4'),
  ('batman-vs-robin-2022-004', 'tony-harris', 'Tony Harris - variante 1:50', 'https://dcuguide.com/images/3/32/Batman_vs._Robin_4_%28Cover_D%29.png', 'https://dcuguide.com/Batman_vs._Robin_4'),
  ('batman-vs-robin-2022-004', 'sweeney-boo', 'Sweeney Boo', 'https://dcuguide.com/images/9/98/Batman_vs._Robin_4_%28Cover_E%29.png', 'https://dcuguide.com/Batman_vs._Robin_4'),
  ('batman-vs-robin-2022-005', 'kelley-jones', 'Kelley Jones', 'https://dcuguide.com/images/9/97/Batman_vs._Robin_5_%28Cover_B%29.png', 'https://dcuguide.com/Batman_vs._Robin_5'),
  ('batman-vs-robin-2022-005', 'christian-ward', 'Christian Ward - variante 1:25', 'https://dcuguide.com/images/a/a1/Batman_vs._Robin_5_%28Cover_C%29.png', 'https://dcuguide.com/Batman_vs._Robin_5'),
  ('batman-vs-robin-2022-005', 'yasmin-flores-montanez', 'Yasmin Flores Montañez - variante 1:50', 'https://dcuguide.com/images/9/9e/Batman_vs._Robin_5_%28Cover_D%29.png', 'https://dcuguide.com/Batman_vs._Robin_5'),
  ('batman-vs-robin-2022-005', 'rafa-sandoval', 'Rafa Sandoval', 'https://dcuguide.com/images/2/22/Batman_vs._Robin_5_%28Cover_E%29.png', 'https://dcuguide.com/Batman_vs._Robin_5'),
  ('batman-vs-robin-2022-005', 'yanick-paquette', 'Yanick Paquette', 'https://dcuguide.com/images/c/c5/Batman_vs._Robin_5_%28Cover_F%29.png', 'https://dcuguide.com/Batman_vs._Robin_5'),
  ('batman-vs-robin-2022-005', 'mahmud-asrar-foil', 'Mahmud Asrar - variante foil 1:100', 'https://dcuguide.com/images/b/b3/Batman_vs._Robin_5_%28Cover_G%29.png', 'https://dcuguide.com/Batman_vs._Robin_5'),
  ('jurassic-league-2022-001', 'juan-gedeon', 'Juan Gedeon', 'https://dcuguide.com/images/b/bb/Jurassic_League_1_%28Cover_B%29.png', 'https://dcuguide.com/Jurassic_League_1'),
  ('jurassic-league-2022-001', 'walter-simonson', 'Walter Simonson - variante 1:25', 'https://dcuguide.com/images/5/59/Jurassic_League_1_%28Cover_C%29.png', 'https://dcuguide.com/Jurassic_League_1'),
  ('jurassic-league-2022-002', 'mike-perkins', 'Mike Perkins', 'https://dcuguide.com/images/b/b3/Jurassic_League_2_%28Cover_B%29.png', 'https://dcuguide.com/Jurassic_League_2'),
  ('jurassic-league-2022-003', 'gustavo-duarte', 'Gustavo Duarte', 'https://dcuguide.com/images/c/cd/Jurassic_League_3_%28Cover_B%29.png', 'https://dcuguide.com/Jurassic_League_3'),
  ('jurassic-league-2022-004', 'brett-booth', 'Brett Booth e Daniel Henriques', 'https://dcuguide.com/images/1/11/Jurassic_League_4_%28Cover_B%29.png', 'https://dcuguide.com/Jurassic_League_4'),
  ('jurassic-league-2022-005', 'jonathan-marks', 'Jonathan Marks', 'https://dcuguide.com/images/e/e9/Jurassic_League_5_%28Cover_B%29.png', 'https://dcuguide.com/Jurassic_League_5'),
  ('jurassic-league-2022-005', 'dan-mora', 'Dan Mora - variante Hispanic Heritage Month', 'https://dcuguide.com/images/4/43/Jurassic_League_5_%28Cover_C%29.png', 'https://dcuguide.com/Jurassic_League_5'),
  ('jurassic-league-2022-006', 'juan-gedeon', 'Juan Gedeon', 'https://dcuguide.com/images/2/26/Jurassic_League_6_%28Cover_B%29.png', 'https://dcuguide.com/Jurassic_League_6'),
  ('unstoppable-doom-patrol-2023-001', 'chris-burnham-scratch', 'Chris Burnham - variante scratch-off', 'https://dcuguide.com/images/8/83/Unstoppable_Doom_Patrol_1_%28Cover_B%29.png', 'https://dcuguide.com/Unstoppable_Doom_Patrol_1'),
  ('unstoppable-doom-patrol-2023-001', 'nathan-szerdy', 'Nathan Szerdy', 'https://dcuguide.com/images/d/d1/Unstoppable_Doom_Patrol_1_%28Cover_C%29.png', 'https://dcuguide.com/Unstoppable_Doom_Patrol_1'),
  ('unstoppable-doom-patrol-2023-001', 'dennis-culver', 'Dennis Culver - variante 1:25', 'https://dcuguide.com/images/b/b0/Unstoppable_Doom_Patrol_1_%28Cover_D%29.png', 'https://dcuguide.com/Unstoppable_Doom_Patrol_1'),
  ('unstoppable-doom-patrol-2023-001', 'chris-burnham-design', 'Chris Burnham - variante de design', 'https://dcuguide.com/images/a/a7/Unstoppable_Doom_Patrol_1_%28Cover_E%29.png', 'https://dcuguide.com/Unstoppable_Doom_Patrol_1'),
  ('unstoppable-doom-patrol-2023-001', 'nathan-szerdy-foil', 'Nathan Szerdy - variante foil 1:50', 'https://dcuguide.com/images/f/f8/Unstoppable_Doom_Patrol_1_%28Cover_F%29.png', 'https://dcuguide.com/Unstoppable_Doom_Patrol_1'),
  ('unstoppable-doom-patrol-2023-001', 'chris-burnham-scratch-g', 'Chris Burnham - variante scratch-off G', 'https://dcuguide.com/images/1/14/Unstoppable_Doom_Patrol_1_%28Cover_G%29.png', 'https://dcuguide.com/Unstoppable_Doom_Patrol_1'),
  ('unstoppable-doom-patrol-2023-001', 'chris-burnham-scratch-h', 'Chris Burnham - variante scratch-off H', 'https://dcuguide.com/images/5/52/Unstoppable_Doom_Patrol_1_%28Cover_H%29.png', 'https://dcuguide.com/Unstoppable_Doom_Patrol_1'),
  ('unstoppable-doom-patrol-2023-001', 'chris-burnham-scratch-i', 'Chris Burnham - variante scratch-off I', 'https://dcuguide.com/images/9/91/Unstoppable_Doom_Patrol_1_%28Cover_I%29.png', 'https://dcuguide.com/Unstoppable_Doom_Patrol_1'),
  ('unstoppable-doom-patrol-2023-001', 'chris-burnham-scratch-j', 'Chris Burnham - variante scratch-off J', 'https://dcuguide.com/images/3/30/Unstoppable_Doom_Patrol_1_%28Cover_J%29.png', 'https://dcuguide.com/Unstoppable_Doom_Patrol_1'),
  ('unstoppable-doom-patrol-2023-001', 'chris-burnham-scratch-k', 'Chris Burnham - variante scratch-off K', 'https://dcuguide.com/images/9/96/Unstoppable_Doom_Patrol_1_%28Cover_K%29.png', 'https://dcuguide.com/Unstoppable_Doom_Patrol_1'),
  ('fury-of-firestorm-2026-001', 'jorge-corona', 'Jorge Corona - variante Next Level card stock', 'https://dcuguide.com/images/8/87/Fury_of_Firestorm_Vol._2_1_%28Cover_B%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_1'),
  ('fury-of-firestorm-2026-001', 'riley-rossmo', 'Riley Rossmo - variante card stock', 'https://dcuguide.com/images/e/eb/Fury_of_Firestorm_Vol._2_1_%28Cover_C%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_1'),
  ('fury-of-firestorm-2026-001', 'chris-burnham', 'Chris Burnham - variante card stock', 'https://dcuguide.com/images/2/28/Fury_of_Firestorm_Vol._2_1_%28Cover_D%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_1'),
  ('fury-of-firestorm-2026-001', 'jeff-lemire', 'Jeff Lemire - variante 1:25 card stock', 'https://dcuguide.com/images/3/30/Fury_of_Firestorm_Vol._2_1_%28Cover_E%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_1'),
  ('fury-of-firestorm-2026-001', 'chris-burnham-foil', 'Chris Burnham - variante foil', 'https://dcuguide.com/images/d/d2/Fury_of_Firestorm_Vol._2_1_%28Cover_F%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_1'),
  ('fury-of-firestorm-2026-001', 'blank', 'Variante em branco card stock', 'https://dcuguide.com/images/b/bc/Fury_of_Firestorm_Vol._2_1_%28Cover_G%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_1'),
  ('fury-of-firestorm-2026-002', 'sanford-greene', 'Sanford Greene - variante card stock', 'https://dcuguide.com/images/6/64/Fury_of_Firestorm_Vol._2_2_%28Cover_B%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_2'),
  ('fury-of-firestorm-2026-002', 'riley-rossmo', 'Riley Rossmo - variante card stock', 'https://dcuguide.com/images/3/38/Fury_of_Firestorm_Vol._2_2_%28Cover_C%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_2'),
  ('fury-of-firestorm-2026-002', 'mark-spears', 'Mark Spears - variante card stock', 'https://dcuguide.com/images/a/a8/Fury_of_Firestorm_Vol._2_2_%28Cover_D%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_2'),
  ('fury-of-firestorm-2026-003', 'todd-nauck', 'Todd Nauck - variante card stock', 'https://dcuguide.com/images/3/30/Fury_of_Firestorm_Vol._2_3_%28Cover_B%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_3'),
  ('fury-of-firestorm-2026-003', 'dustin-nguyen', 'Dustin Nguyen - variante card stock', 'https://dcuguide.com/images/0/02/Fury_of_Firestorm_Vol._2_3_%28Cover_C%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_3'),
  ('fury-of-firestorm-2026-003', 'stephen-green', 'Stephen Green - variante card stock', 'https://dcuguide.com/images/b/be/Fury_of_Firestorm_Vol._2_3_%28Cover_D%29.png', 'https://dcuguide.com/Fury_of_Firestorm_Vol._2_3'),
  ('new-champion-of-shazam-001', 'joshua-middleton', 'Joshua Middleton', 'https://dcuguide.com/images/1/12/New_Champion_of_Shazam%21_1_%28Cover_B%29.png', 'https://dcuguide.com/New_Champion_of_Shazam%21_1'),
  ('new-champion-of-shazam-001', 'gary-frank', 'Gary Frank - variante 1:25', 'https://dcuguide.com/images/e/e4/New_Champion_of_Shazam%21_1_%28Cover_C%29.png', 'https://dcuguide.com/New_Champion_of_Shazam%21_1'),
  ('new-golden-age-001', 'jay-hero', 'Jay Hero - variante card stock', 'https://dcuguide.com/images/2/22/New_Golden_Age_1_%28Cover_B%29.png', 'https://dcuguide.com/New_Golden_Age_1'),
  ('new-golden-age-001', 'todd-nauck', 'Todd Nauck - variante card stock', 'https://dcuguide.com/images/f/f8/New_Golden_Age_1_%28Cover_C%29.png', 'https://dcuguide.com/New_Golden_Age_1'),
  ('new-golden-age-001', 'mike-allred', 'Mike Allred - variante card stock', 'https://dcuguide.com/images/3/31/New_Golden_Age_1_%28Cover_D%29.png', 'https://dcuguide.com/New_Golden_Age_1'),
  ('new-golden-age-001', 'david-talaski', 'David Talaski - variante card stock', 'https://dcuguide.com/images/8/8d/New_Golden_Age_1_%28Cover_E%29.png', 'https://dcuguide.com/New_Golden_Age_1'),
  ('new-golden-age-001', 'dan-hipp', 'Dan Hipp - variante 1:25 card stock', 'https://dcuguide.com/images/c/c1/New_Golden_Age_1_%28Cover_F%29.png', 'https://dcuguide.com/New_Golden_Age_1'),
  ('new-golden-age-001', 'mike-allred-foil', 'Mike Allred - variante foil 1:50', 'https://dcuguide.com/images/3/35/New_Golden_Age_1_%28Cover_G%29.png', 'https://dcuguide.com/New_Golden_Age_1'),
  ('new-golden-age-001', 'david-talaski-foil', 'David Talaski - variante foil 1:00', 'https://dcuguide.com/images/e/ee/New_Golden_Age_1_%28Cover_H%29.png', 'https://dcuguide.com/New_Golden_Age_1'),
  ('death-of-superman-30th-anniversary-001', 'ivan-reis-danny-miki', 'Ivan Reis e Danny Miki - Funeral for a Friend', 'https://static.dc.com/sites/default/files/imce/2022/07-JUL/DofSUPERMAN_CVR_var_fnl_62e052d80645e3.47964538.jpeg', 'https://www.dc.com/blog/2022/07/27/death-of-superman-anniversary-special-with-stories-from-original-teams'),
  ('death-of-superman-30th-anniversary-001', 'francesco-mattina-doomsday', 'Francesco Mattina - variante Doomsday', 'https://static.dc.com/sites/default/files/imce/2022/07-JUL/DeathOfSuperman%20_Doomsday%20cover_62e0539d634189.83927545.jpeg', 'https://www.dc.com/blog/2022/07/27/death-of-superman-anniversary-special-with-stories-from-original-teams'),
  ('death-of-superman-30th-anniversary-001', 'dan-jurgens-brett-breeding-polybag', 'Dan Jurgens e Brett Breeding - variante polybag', 'https://static.dc.com/sites/default/files/imce/2022/07-JUL/Death%20of%20Superman%2030th%20Anniversary%20Polybag%20Variant_62e053679b7790.78703788.jpg', 'https://www.dc.com/blog/2022/07/27/death-of-superman-anniversary-special-with-stories-from-original-teams'),
  ('immortal-legend-batman-2025-002', 'michael-cho', 'Michael Cho - variante card stock', 'https://i.ebayimg.com/images/g/DaEAAeSw4TZo0b4d/s-l1200.jpg', 'https://www.comics.org/issue/2772077/'),
  ('immortal-legend-batman-2025-003', 'derrick-chew', 'Derrick Chew - variante card stock', 'https://iwt.sfo2.cdn.digitaloceanspaces.com/cbr-covers/141826b04d5eec966f2eb64a2b3f3d69_xl.jpg', 'https://www.comics.org/issue/2778692/'),
  ('batman-killing-time-2022-002', 'kael-ngu', 'Kael Ngu - variante card stock', 'https://everythingcomics.ca/cdn/shop/products/DCDL224779.jpg?v=1691530542', 'https://www.comics.org/issue/2495177/'),
  ('batman-one-bad-day-2022-006', 'jim-lee-scott-williams', 'Jim Lee, Scott Williams e Alex Sinclair', 'https://shop.thirdeyecomics.com/cdn/shop/products/dc-comics-comic-books-batman-one-bad-day-bane-1-one-shot-cvr-b-jim-lee-scott-williams-alex-sinclair-card-stock-var-76194137739100121-1122dc059-38714722550012.jpg?v=1762366117', 'https://www.comics.org/issue/2481325/'),
  ('batman-catwoman-gotham-war-2023-001', 'kael-ngu', 'Kael Ngu - variante card stock', 'https://storage.googleapis.com/hipcomic/p/92fede0eb8a7f46e28950251c3c2876a.jpg', 'https://www.comics.org/issue/2564985/'),
  ('batman-superman-worlds-finest-2022-001', 'jim-lee-scott-williams', 'Jim Lee e Scott Williams - variante card stock', 'https://i.ebayimg.com/images/g/DOQAAOSwrghiphXx/s-l1200.jpg', 'https://www.comics.org/issue/2378342/'),
  ('batman-urban-legends-2021-001', 'kael-ngu', 'Kael Ngu - variante Grifter', 'https://dc.fandom.com/wiki/Special:FilePath/Batman_Urban_Legends_Vol_1_1_Ngu_Variant.jpg', 'https://www.comics.org/issue/2206717/'),
  ('joker-2021-001', 'rafael-grassetti', 'Rafael Grassetti - variante Scorpion Comics', 'https://img.hipcomic.com/p/3621a5cfff21ba771eb315464ee224b5-800.jpg', 'https://www.comics.org/issue/2254770/'),
  ('deathstroke-inc-2021-001', 'dima-ivanov', 'Dima Ivanov - variante card stock', 'https://www.midtowncomics.com/images/PRODUCT/XL/2025390_xl.jpg', 'https://www.comics.org/issue/2266190/'),
  ('dark-crisis-2022-01', 'kael-ngu-jim-lee-homage', 'Kael Ngu - homenagem a Jim Lee, variante minimal trade dress', 'https://i.ebayimg.com/images/g/tpoAAOSwgatkrde2/s-l1200.jpg', 'https://www.comics.org/issue/2409236/'),
  ('batman-superman-worlds-finest-2022-001', 'artgerm', 'Stanley Artgerm Lau - variante card stock', 'https://i.ebayimg.com/images/g/rpQAAOSwS2piphN5/s-l1200.jpg', 'https://www.comics.org/series/182645/covers/?sort=on_sale_date'),
  ('batman-superman-worlds-finest-2022-001', 'jason-fabok', 'Jason Fabok - variante card stock', 'https://www.midtowncomics.com/images/PRODUCT/XL/2074219_xl.jpg', 'https://www.comics.org/issue/2378215/'),
  ('batman-superman-worlds-finest-2022-001', 'chip-zdarsky', 'Chip Zdarsky - variante Batman/Superman slap', 'https://storage.googleapis.com/hipcomic/p/6d8ed27af1d737202f11839be37e99a0.jpg', 'https://www.comics.org/series/182645/covers/?sort=on_sale_date'),
  ('batman-urban-legends-2021-001', 'david-finch', 'David Finch - variante Red Hood', 'https://cdn.shopify.com/s/files/1/2544/7404/products/BATMANURBANLEGENDS_1CVRBDAVIDFINCHBATMANREDHOODVAR_580x%402x.jpg?v=1611105947', 'https://www.comics.org/issue/2205583/'),
  ('deathstroke-inc-2021-001', 'francesco-mattina', 'Francesco Mattina - variante card stock', 'https://www.midtowncomics.com/images/PRODUCT/XL/2025387_xl.jpg', 'https://www.comics.org/issue/2266190/'),
  ('deathstroke-inc-2021-001', 'adam-hughes', 'Adam Hughes - variante Black Canary', 'https://i.ebayimg.com/images/g/e9IAAOSwfV9mje0C/s-l1200.jpg', 'https://www.comics.org/issue/2266190/'),
  ('dark-crisis-2022-01', 'greg-capullo-foil', 'Greg Capullo e Jonathan Glapion - variante foil', 'https://myshopville.com/cdn/shop/files/Dark-Crisis-_1-Greg-Capullo-Cover-I-Foil-Variant-2022--1100-Cover.jpg?v=1736273722', 'https://www.comics.org/series/185767/details/'),
  ('dark-crisis-2022-01', 'bruno-redondo', 'Bruno Redondo - variante card stock', 'https://storage.googleapis.com/hipcomic/p/857e2b11ed008257128d8988aea898d2-800.jpg', 'https://www.comics.org/series/185767/covers/'),
  ('infinite-frontier-2021-001', 'bryan-hitch', 'Bryan Hitch - variante cardstock', 'https://www.supermanhomepage.com/clickandbuilds/SupermanHomepage/wp-content/uploads/2021/05/INFINITE_FRONTIER_Cv1_var.jpg', 'https://www.comics.org/issue/2233052/'),
  ('dc-all-in-2024-001', 'john-giang', 'John Giang - variante cardstock wraparound', 'https://sequentialartcomics.com/cdn/shop/files/0824DC015_3af5a894-fdaa-4b9f-8aee-ae35f52f00a5.jpg?v=1766837938', 'https://www.comics.org/issue/2658454/'),
  ('joker-2021-002', 'lee-bermejo', 'Lee Bermejo - variante', 'https://www.cardboardmemories.ca/cdn/shop/products/3357998a1fa7014d43b7a78984d1977b_934x700.jpg?v=1712561859', 'https://www.cardboardmemories.ca/products/dc-comics-joker-002-lee-bermejo-variant-edition-7146'),
  ('joker-2021-002', 'brian-stelfreeze', 'Brian Stelfreeze - variante', 'https://media.mycomicshop.com/n_iv/120/5775363.jpg', 'https://www.mycomicshop.com/search?TID=52799130&mingr=0'),
  ('joker-2021-003', 'david-finch', 'David Finch - variante', 'https://goldenapplecomics.com/cdn/shop/products/179076-hr.jpg?v=1614173761', 'https://www.comics.org/issue/2222139/'),
  ('joker-2021-003', 'gary-frank', 'Gary Frank - variante', 'https://shop.thirdeyecomics.com/cdn/shop/products/dc-comics-comic-books-joker-3-cvr-c-frank-cardstock-var-76194137222800331-mar217067-38929792205052_1800x.jpg?v=1762385945', 'https://shop.thirdeyecomics.com/products/joker-3-cvr-c-frank-cardstock-var'),
  ('joker-2021-003', 'riccardo-federici', 'Riccardo Federici - variante sketch', 'https://media.mycomicshop.com/n_iv/120/5808557.jpg', 'https://www.mycomicshop.com/search?TID=52799130&mingr=0'),
  ('joker-2021-004', 'riccardo-federici', 'Riccardo Federici - variante 1:25', 'https://comickingdomcreative.com/cdn/shop/products/Joker41-25RiccardoFederici_1200x1200.jpg?v=1625589912', 'https://www.comics.org/series/170432/covers/?page=1'),
  ('batman-and-robin-2023-001', 'artgerm', 'Stanley Artgerm Lau - variante card stock', 'https://mlpnk72yciwc.i.optimole.com/cqhiHLc.IIZS~2ef73/w%3Aauto/h%3Aauto/q%3A75/https%3A/bleedingcool.com/wp-content/uploads/2023/04/batman-And-Robin-1a.jpg', 'https://www.bleedingcool.com/comics/stanley-artgerm-lau-discovers-that-dc-character-white-rabbit-exists/'),
  ('batman-and-robin-2023-001', 'kael-ngu', 'Kael Ngu - variante card stock', 'https://www.alternateworldscomics.com/cdn/shop/products/202306-0000424574.jpg?v=1694458793', 'https://www.alternateworldscomics.com/products/0723dc030-batman-and-robin-1'),
  ('cyborg-2023-001', 'tom-raney', 'Tom Raney - variante card stock', 'https://image.keycollectorcomics.com/media/d66ebc50-8c0b-4744-99a0-1be64b62dd9c.jpg?format=webp&height=675&quality=80', 'https://aqua.gjovaag.com/w/images/0/08/20230317_dc_connect_34.pdf'),
  ('dc-ko-2025-01', 'mike-del-mundo', 'Mike Del Mundo - variante card stock', 'https://dcuguide.com/Special:FilePath/DC_K.O._1_%28Cover_B%29.png', 'https://www.dc.com/blog/2025/07/16/dc-comics-announces-dc-k-o-event'),
  ('dc-ko-2025-01', 'mark-spears', 'Mark Spears - variante Darkseid', 'https://dcuguide.com/Special:FilePath/DC_K.O._1_%28Cover_C%29.png', 'https://www.dc.com/blog/2025/07/16/dc-comics-announces-dc-k-o-event'),
  ('dc-ko-2025-01', 'dan-mora', 'Dan Mora - variante bracket wraparound', 'https://dcuguide.com/Special:FilePath/DC_K.O._1_%28Cover_H%29.png', 'https://www.dc.com/blog/2025-08-29/dc-reveals-all-32-tournament-contestants-in-stunning-dan-mora-cover-for-dc-k-o-1'),
  ('challengers-unknown-2025-01', 'sean-izaakse', 'Sean Izaakse e Romulo Fajardo Jr. - variante card stock', 'https://oxfordcomicsandgames.com/cdn/shop/files/202409-0000473964.jpg?v=1734373565&width=1080', 'https://oxfordcomicsandgames.com/products/1024dc083-challengers-of-the-unknown-1'),
  ('one-star-squadron-2022-01', 'steve-pugh', 'Steve Pugh - variante card stock', 'https://www.midtowncomics.com/images/PRODUCT/XL/2052304_xl.jpg', 'https://www.midtowncomics.com/p/2052304-onestar-squadron-1-cover-b-variant-steve-pugh-card-stock-cover'),
  ('shadow-war-2022-01', 'dan-mora', 'Dan Mora - variante 1:25', 'https://www.comicsbox.it/cover/SHWRALPHA_001C.jpg', 'https://www.comicsbox.it/albo/SHWRALPHA_001C'),
  ('shadow-war-2022-01', 'viktor-bogdanovic', 'Viktor Bogdanovic - variante', 'https://www.comicsbox.it/cover/SHWRALPHA_001B.jpg', 'https://www.comicsbox.it/albo/SHWRALPHA_001B'),
  ('shadow-war-2022-02', 'roger-cruz', 'Roger Cruz, Victor Olazaba e Luis Guerrero - variante 1:25', 'https://www.comicsbox.it/cover_dc/BATMAN3_122C.jpg', 'https://www.comicsbox.it/albo/BATMAN3_122C'),
  ('shadow-war-2022-03', 'chris-burnham', 'Chris Burnham - variante', 'https://media.mycomicshop.com/n_iv/600/6276131.jpg', 'https://www.mycomicshop.com/search?ItemID=60314705'),
  ('shadow-war-2022-09', 'mikel-janin', 'Mikel Janín - variante', 'https://www.comicsbox.it/cover_dc/SHWROMEGA_001B.jpg', 'https://www.comicsbox.it/albo/SHWROMEGA_001B'),
  ('shadow-war-2022-09', 'james-stokoe', 'James Stokoe - variante 1:25', 'https://www.comicsbox.it/cover_dc/SHWROMEGA_001C.jpg', 'https://www.comicsbox.it/albo/SHWROMEGA_001C'),
  ('series-absolute-power-2024-01', 'reference-cover', 'Capa de referência', 'https://static.dc.com/2024-06/AP_Cv1_00111_DIGITAL-1.jpg', 'https://www.dc.com/comics/absolute-power-2024/absolute-power-1'),
  ('series-atom-project-2025-01', 'reference-cover', 'Capa de referência', 'https://i.postimg.cc/Wbgvm6CV/LJPA1-001.jpg', 'https://www.dc.com/comics/justice-league-the-atom-project-2025/justice-league-the-atom-project-1'),
  ('fire-ice-smallville-2023-01', 'jen-bartel', 'Jen Bartel - capa variante', 'https://goldenapplecomics.com/cdn/shop/files/FIWTS_Cv1_var_BARTEL_00131.jpg?v=1691765351', 'https://goldenapplecomics.com/products/76194138063600131'),
  ('series-flash-fastest-2022-01', 'reference-cover', 'Capa de referência', 'https://i.imgur.com/NugdMhw.jpg', 'https://www.comics.org/series/'),
  ('series-green-lantern-2021-01', 'reference-cover', 'Capa de referência', 'https://zonafantasmanet.files.wordpress.com/2023/05/green-lantern-2021-001-000_med.jpg', 'https://www.comics.org/series/'),
  ('series-green-lantern-2023-01', 'reference-cover', 'Capa de referência', 'https://i.postimg.cc/TYn1MCqn/Green-Lantern-2023-001-000.jpg', 'https://www.comics.org/series/'),
  ('series-green-lantern-war-journal-2023-01', 'reference-coveusou admer', 'Capa de referência', 'https://media.mycomicshop.com/n_iv/600/7160598.jpg', 'https://www.mycomicshop.com/search?TID=59327960'),
  ('series-justice-godzilla-kong-2023-01', 'jim-lee', 'Jim Lee, Scott Williams e Alex Sinclair - variante', 'https://storage.googleapis.com/hipcomic/p/c59817cb3cf7efa0947ac7ff7a378e08-800.jpg', 'https://www.hipcomic.com/listing/justice-league-vs-godzilla-vs-kong-1-cvr-b-jim-lee-variant-dc-2023-nm/13694259'),
  ('series-justice-league-unlimited-2025-01', 'reference-cover', 'Capa de referência', 'https://i.imgur.com/iIHPh8I.jpg', 'https://www.comics.org/series/'),
  ('series-justice-society-2023-01', 'jerry-ordway', 'Jerry Ordway - variante 1:25', 'https://www.cgc-emporium.com/cdn/shop/products/STL249692.jpg?v=1669424681&width=1920', 'https://www.cgc-emporium.com/products/justicesocietyofamerica-1cvrd1-25ordwayvarsep223333'),
  ('series-knight-terrors-2023-01', 'mico-suayan', 'Mico Suayan - variante card stock', 'https://marticomics.com/cdn/shop/files/KnightTerrorsActionComics_1_of2_CoverBMicoSuayanCardStockVariant.jpg?v=1689936718&width=1445', 'https://marticomics.com/products/knight-terrors-action-comics-1-of-2-cover-b-mico-suayan-card-stock-variant-25-july-2023'),
  ('series-lazarus-planet-2023-01', 'reference-cover', 'Capa de referência', 'https://i.postimg.cc/YSpm7P2T/Lazarus-Planet-2023-Alpha-001-000.jpg', 'https://www.comics.org/series/'),
  ('series-monkey-prince-2022-01', 'anand-radhakrishnan', 'Anand Radhakrishnan - variante', 'https://www.midtowncomics.com/images/PRODUCT/XL/2066784_xl.jpg', 'https://www.midtowncomics.com/product/2066784'),
  ('series-new-gods-2025-01', 'reference-cover', 'Capa de referência', 'https://i.postimg.cc/SQ1pd9Lh/ND1-001.jpg', 'https://www.comics.org/series/'),
  ('series-next-batman-second-son-2021-01', 'reference-cover', 'Capa de referência', 'https://comicvine.gamespot.com/a/uploads/original/6/67663/7824353-01.jpg', 'https://www.comics.org/series/'),
  ('series-nubia-amazons-2021-01', 'maika-sozo', 'Maika Sozo - variante', 'https://www.stadiumcomics.com/cdn/shop/products/0821DC070_1024x1024.jpg?v=1626461494', 'https://www.stadiumcomics.com/products/nubia-and-the-amazons-1-pre-order'),
  ('series-penguin-2023-01', 'reference-cover', 'Capa de referência', 'https://i.postimg.cc/43W4f69V/00000.jpg', 'https://www.comics.org/series/'),
  ('series-poison-ivy-2022-01', 'warren-louw', 'Warren Louw - variante', 'https://retconcomics.com/cdn/shop/products/0422DC033_2048x.jpg?v=1654894674', 'https://retconcomics.com/products/poison-ivy-1'),
  ('series-power-girl-special-2023-01', 'reference-cover', 'Capa de referência', 'https://i.ibb.co/LddHW6n/Pdrs01-001.jpg', 'https://www.comics.org/series/'),
  ('series-question-watchtower-2024-01', 'danny-earls', 'Danny Earls - variante 1:25', 'https://i.ebayimg.com/images/g/ZLgAAOSwbYlnRkwv/s-l1200.jpg', 'https://www.ebay.com/itm/296840833595'),
  ('series-robin-2021-01', 'reference-cover', 'Capa de referência', 'https://zonafantasmanet.files.wordpress.com/2021/05/robin-2021-001-000_med.jpg', 'https://www.comics.org/series/'),
  ('series-shazam-2021-01', 'reference-cover', 'Capa de referência', 'https://comicvine.gamespot.com/a/uploads/original/6/67663/8069718-01.jpg', 'https://www.comics.org/series/'),
  ('series-shazam-2023-01', 'evan-doc-shaner', 'Evan Doc Shaner - variante 1:25', 'https://storage.googleapis.com/hipcomic/p/b179a2be557429a39a402c0a0f2edc50.jpg', 'https://www.hipcomic.com/listing/shazam-1-125-evan-doc-shaner-variant-mark-waid-dan-mora-2023-dc-nm/12635545'),
  ('series-stargirl-lost-children-2022-01', 'mayo-naito', 'Mayo Sen Naito - variante 1:25', 'https://thecomicbookshoppe.com/cdn/shop/products/STL250390.jpg?v=1676980816&width=1946', 'https://thecomicbookshoppe.com/products/sep223337-stargirl-the-lost-children-1-of-6-cvr-c-125-naito'),
  ('series-superboy-tomorrow-2023-01', 'george-kambadais', 'George Kambadais - variante', 'https://image.keycollectorcomics.com/media/980c99bc-160c-467e-89e2-216f5150fc52.jpg', 'https://www.keycollectorcomics.com/issue/superboy-the-man-of-tomorrow-1-1%2C665847/'),
  ('series-superman-2023-01', 'jamal-campbell', 'Jamal Campbell - variante 1:100', 'https://i.ebayimg.com/images/g/mnMAAOSwlTpj-PwV/s-l1200.jpg', 'https://www.ebay.com/itm/165955944580'),
  ('series-superman-kal-el-returns-2022-01', 'travis-moore', 'Travis Moore e Tymir Bovalin - variante', 'https://www.cgc-emporium.com/cdn/shop/products/STL250411.jpg?v=1669424706&width=1445', 'https://www.cgc-emporium.com/products/supermankalelreturnsspeconeshotcvrbmooresep223363'),
  ('series-superman-lost-2023-01', 'reference-cover', 'Capa de referência', 'https://i.imgur.com/sAUqRtn.jpg', 'https://www.comics.org/series/'),
  ('series-superman-son-kal-el-2021-01', 'john-timms', 'John Timms - variante', 'https://goldenapplecomics.com/cdn/shop/products/unnamed_fef4b152-1ceb-4b7b-b16d-1775c0799920.png?v=1628107772', 'https://goldenapplecomics.com/products/superman-son-of-kal-el-1-2nd-print-john-timms-variant-07-27-2021-dc'),
  ('series-swamp-thing-2021-01', 'reference-cover', 'Capa de referência', 'https://i.imgur.com/yWOZXir.jpg', 'https://www.comics.org/series/'),
  ('series-titans-2023-01', 'dan-mora', 'Dan Mora - variante card stock', 'https://www.midtowncomics.com/images/PRODUCT/XL/2199939_xl.jpg', 'https://www.midtowncomics.com/product/2199939'),
  ('series-trial-amazons-2022-01', 'jen-bartel', 'Jen Bartel - variante exclusiva', 'https://storage.googleapis.com/hipcomic/p/a3769f0489587e20d2724a2cc88ba128.jpg', 'https://www.hipcomic.com/listing/trial-of-the-amazons-1-exclusive-jen-bartel-team-variant-wraparound-cover/11499579'),
  ('war-earth-3-2022-01', 'reference-cover', 'Capa de referência', 'https://i.postimg.cc/q7SmwJ88/War-for-Earth-3-2022-001-000.jpg', 'https://www.comics.org/series/'),
  ('war-earth-3-2022-01', 'gleb-melnikov', 'Gleb Melnikov - variante', 'https://static.wikia.nocookie.net/marvel_dc/images/c/ce/War_for_Earth-3_Vol_1_1_Textless_Melnikov_Variant.jpg/revision/latest?cb=20220301234711', 'https://dc.fandom.com/wiki/File:War_for_Earth-3_Vol_1_1_Textless_Melnikov_Variant.jpg'),
  ('war-earth-3-2022-01', 'liam-sharp', 'Liam Sharp - variante 1:25', 'https://static.wikia.nocookie.net/marvel_dc/images/1/11/War_for_Earth-3_Vol_1_1_Textless_Sharp_Variant.jpg/revision/latest?cb=20220301234403', 'https://dc.fandom.com/wiki/File:War_for_Earth-3_Vol_1_1_Textless_Sharp_Variant.jpg'),
  ('war-earth-3-2022-01', 'guillem-march', 'Guillem March - variante 1:50', 'https://static.wikia.nocookie.net/marvel_dc/images/5/5c/War_for_Earth-3_Vol_1_1_Textless_March_Variant.jpg/revision/latest?cb=20220301234157', 'https://dc.fandom.com/wiki/File:War_for_Earth-3_Vol_1_1_Textless_March_Variant.jpg'),
  ('war-earth-3-2022-02', 'gleb-melnikov', 'Gleb Melnikov - variante card stock', 'https://static.wikia.nocookie.net/marvel_dc/images/a/a7/War_for_Earth-3_Vol_1_2_Textless_Variant.jpg/revision/latest?cb=20220329103918', 'https://dc.fandom.com/wiki/File:War_for_Earth-3_Vol_1_2_Textless_Variant.jpg'),
  ('series-we-are-yesterday-2025-01', 'reference-cover', 'Capa de referência', 'https://i.imgur.com/bWQIL4g.jpg', 'https://www.comics.org/series/'),
  ('series-wildcats-2023-01', 'reference-cover', 'Capa de referência', 'https://i.postimg.cc/MT94FJJc/001.jpg', 'https://www.comics.org/series/'),
  ('series-wonder-girl-2021-01', 'bilquis-evely', 'Bilquis Evely - variante card stock', 'https://i.ebayimg.com/images/g/tL4AAOSwVphgp15G/s-l1200.jpg', 'https://www.ebay.com/itm/363405256660'),
  ('series-wonder-woman-2023-01', 'reference-cover', 'Capa de referência', 'https://i.postimg.cc/Zn54HP6d/00000.jpg', 'https://www.comics.org/series/'),
  -- Teen Titans Academy: as artes abaixo são hospedadas por lojas/serviços externos;
  -- a identificação das edições e dos artistas foi conferida no catálogo do GCD.
  ('teen-titans-academy-001', 'jamal-campbell', 'Jamal Campbell', 'https://dcuguide.com/images/d/d5/Teen_Titans_Academy_1_%28Cover_B%29.png', 'https://dcuguide.com/File:Teen_Titans_Academy_1_%28Cover_B%29.png'),
  ('teen-titans-academy-002', 'philip-tan', 'Philip Tan e Elmer Santos', 'https://goldenapplecomics.com/cdn/shop/products/0221DC077.jpg?v=1616857854', 'https://goldenapplecomics.com/products/176144'),
  ('teen-titans-academy-003', 'philip-tan', 'Philip Tan e Elmer Santos', 'https://static.pulps.fr/img/no-cat/full/0321DC094.jpg', 'https://www.comics.org/series/171160/covers/'),
  ('teen-titans-academy-004', 'stephen-byrne-pride', 'Stephen Byrne - DC Pride', 'https://sanctumsanctorumcomics.com/cdn/shop/products/182436-hr.jpg?v=1616636898&width=1946', 'https://www.dc.com/blog/2021/03/11/dc-announces-dc-pride-anthology-comic-to-arrive-june-8-and-more'),
  ('teen-titans-academy-005', 'philip-tan', 'Philip Tan e Elmer Santos', 'https://goldenapplecomics.com/cdn/shop/products/185505-hr.jpg?v=1619732894', 'https://goldenapplecomics.com/products/185505'),
  ('teen-titans-academy-anuario', 'rafa-sandoval', 'Rafa Sandoval, Jordi Tarragona e Alejandro Sánchez', 'https://blackdragoncomix.com/cdn/shop/products/TeenTitansAcademyYearbook2021_1CoverBVariantRafaSandovalCardStockCover_1200x1200.jpg?v=1624589460', 'https://www.comics.org/series/171160/covers/')
on conflict (item_id, variant_key) do update
set label = excluded.label,
    cover_url = excluded.cover_url,
    source_url = excluded.source_url;

