-- Execute este arquivo no SQL Editor do Supabase.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[A-Za-z0-9_]{3,24}$'),
  account_email text unique,
  avatar_url text,
  plan text not null default 'free' check (plan in ('free', 'premium', 'moderator', 'admin')),
  title text,
  profile_hidden boolean not null default false,
  is_banned boolean not null default false,
  silenced_until timestamptz,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists account_email text;
alter table public.profiles add column if not exists title_color text default '#ffd45c';
alter table public.profiles add column if not exists shelf_saved_public boolean not null default true;
alter table public.profiles add column if not exists shelf_series_public boolean not null default true;
alter table public.profiles add column if not exists shelf_read_public boolean not null default true;
alter table public.profiles add column if not exists shelf_completed_public boolean not null default true;
alter table public.profiles add column if not exists shelf_liked_public boolean not null default true;
alter table public.profiles add column if not exists shelf_categories jsonb not null default '[]'::jsonb;
alter table public.profiles add column if not exists profile_hidden boolean not null default false;
alter table public.profiles add column if not exists is_banned boolean not null default false;
alter table public.profiles add column if not exists silenced_until timestamptz;
alter table public.profiles add column if not exists likes_public boolean not null default true;
alter table public.profiles add column if not exists allow_mentions boolean not null default true;
alter table public.profiles add column if not exists allow_messages boolean not null default true;
alter table public.profiles add column if not exists notifications_enabled boolean not null default true;
alter table public.profiles add column if not exists shelf_blogs_public boolean not null default true;
alter table public.profiles add column if not exists xp integer not null default 0;
alter table public.profiles add column if not exists level integer not null default 1;
alter table public.profiles add column if not exists daily_streak integer not null default 0;
alter table public.profiles add column if not exists last_checkin_at timestamptz;
alter table public.profiles drop constraint if exists profiles_plan_check;
alter table public.profiles add constraint profiles_plan_check check (plan in ('free', 'premium', 'moderator', 'admin'));
create unique index if not exists profiles_account_email_key on public.profiles(account_email) where account_email is not null;

create table if not exists public.profile_xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null,
  event_key text not null,
  xp integer not null check (xp > 0),
  created_at timestamptz not null default now(),
  unique (user_id, event_key)
);
create index if not exists profile_xp_events_created_idx on public.profile_xp_events(created_at desc);
create index if not exists profile_xp_events_user_created_idx on public.profile_xp_events(user_id, created_at desc);

create table if not exists public.publisher_settings (
  publisher_key text primary key,
  publisher_name text not null,
  cover_url text,
  is_pinned boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 3 and 140),
  excerpt text not null default '' check (char_length(excerpt) <= 500),
  content_html text not null default '',
  cover_url text,
  image_2_url text,
  image_3_url text,
  status text not null default 'published' check (status in ('draft', 'published')),
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);
create index if not exists blog_posts_published_idx on public.blog_posts(status, is_featured desc, published_at desc);
create index if not exists blog_posts_author_idx on public.blog_posts(author_id, updated_at desc);

create table if not exists public.blog_likes (
  blog_id bigint not null references public.blog_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blog_id, user_id)
);
create index if not exists blog_likes_blog_idx on public.blog_likes(blog_id);

create table if not exists public.blog_comments (
  id bigint generated by default as identity primary key,
  blog_id bigint not null references public.blog_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  parent_id bigint references public.blog_comments(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 1000),
  created_at timestamptz not null default now()
);
alter table public.blog_comments add column if not exists parent_id bigint references public.blog_comments(id) on delete cascade;
create index if not exists blog_comments_blog_idx on public.blog_comments(blog_id, created_at desc);

create table if not exists public.blog_comment_likes (
  blog_comment_id bigint not null references public.blog_comments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blog_comment_id, user_id)
);
create index if not exists blog_comment_likes_comment_idx on public.blog_comment_likes(blog_comment_id);

create table if not exists public.blog_saves (
  blog_id bigint not null references public.blog_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blog_id, user_id)
);
create index if not exists blog_saves_user_idx on public.blog_saves(user_id, created_at desc);

insert into storage.buckets (id, name, public) values ('blog-images', 'blog-images', true) on conflict (id) do nothing;

create table if not exists public.profile_follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  type text not null default 'system',
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 500),
  href text,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id) where read_at is null;

do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then
  null;
end;
$$;

create or replace function public.create_notification(
  p_user_id uuid,
  p_type text,
  p_title text,
  p_body text,
  p_actor_id uuid default null,
  p_href text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if p_user_id is null or p_user_id = p_actor_id or not exists (select 1 from public.profiles where id = p_user_id and notifications_enabled) then return; end if;
  insert into public.notifications(user_id, actor_id, type, title, body, href, metadata)
  values (p_user_id, p_actor_id, p_type, p_title, p_body, p_href, coalesce(p_metadata, '{}'::jsonb));
end;
$$;

revoke execute on function public.create_notification(uuid, text, text, text, uuid, text, jsonb) from anon, authenticated;

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  check (sender_id <> recipient_id)
);

create index if not exists chat_messages_sender_recipient_idx on public.chat_messages(sender_id, recipient_id, created_at desc);
create index if not exists chat_messages_expires_idx on public.chat_messages(expires_at);

create table if not exists public.chat_rooms (
  id text primary key,
  name text not null unique,
  access text not null default 'public' check (access in ('public', 'premium', 'staff'))
);

insert into public.chat_rooms (id, name, access) values
  ('geral', 'Chat Geral', 'public'),
  ('decenautas', 'Decenautas', 'public'),
  ('marvetes', 'Marvetes', 'public'),
  ('leitores-colecionadores', 'Leitores e Colecionadores', 'premium'),
  ('staff', 'Chat da Staff', 'staff')
on conflict (id) do update set name = excluded.name, access = excluded.access;

alter table public.chat_messages add column if not exists room_id text references public.chat_rooms(id) on delete cascade;
alter table public.chat_messages alter column recipient_id drop not null;
alter table public.chat_messages drop constraint if exists chat_messages_destination_check;
alter table public.chat_messages add constraint chat_messages_destination_check check (
  (room_id is null and recipient_id is not null) or (room_id is not null and recipient_id is null)
);
create index if not exists chat_messages_room_created_idx on public.chat_messages(room_id, created_at desc);

do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then
  null;
end;
$$;

create or replace function public.purge_expired_chat_messages()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  delete from public.chat_messages where expires_at <= now();
  return new;
end;
$$;

drop trigger if exists purge_expired_chat_messages_trigger on public.chat_messages;
create trigger purge_expired_chat_messages_trigger
before insert on public.chat_messages
for each statement execute procedure public.purge_expired_chat_messages();

create table if not exists public.shelf_collections (
  id text primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 60),
  cover_url text,
  is_public boolean not null default true,
  item_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.shelf_collections add column if not exists collection_type text not null default 'comic';
alter table public.shelf_collections add column if not exists blog_ids jsonb not null default '[]'::jsonb;
alter table public.shelf_collections add column if not exists is_featured boolean not null default false;
alter table public.shelf_collections add column if not exists cover_styles jsonb not null default '{}'::jsonb;
alter table public.shelf_collections add column if not exists cover_choices jsonb not null default '{}'::jsonb;
alter table public.shelf_collections drop constraint if exists shelf_collections_type_check;
alter table public.shelf_collections add constraint shelf_collections_type_check check (collection_type in ('comic', 'blog'));

insert into public.shelf_collections (id, owner_id, name, cover_url, is_public, item_ids)
select category->>'id', profiles.id, category->>'name', category->>'coverUrl', coalesce((category->>'isPublic')::boolean, true), coalesce(category->'itemIds', '[]'::jsonb)
from public.profiles
cross join lateral jsonb_array_elements(coalesce(profiles.shelf_categories, '[]'::jsonb)) as category
where category->>'id' is not null and category->>'name' is not null
on conflict (id) do nothing;

alter table public.profiles drop column if exists shelf_categories;

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, item_id)
);

-- Capas oficiais e preferência de capa dos usuários Premium.
create table if not exists public.comic_cover_variants (
  item_id text not null,
  variant_key text not null,
  label text not null check (char_length(label) between 1 and 80),
  cover_url text not null check (cover_url ~ '^https://static[.]dc[.]com/'),
  source_url text,
  created_at timestamptz not null default now(),
  primary key (item_id, variant_key)
);

alter table public.comic_cover_variants drop constraint if exists comic_cover_variants_cover_url_check;
alter table public.comic_cover_variants add constraint comic_cover_variants_cover_url_check check (
  cover_url ~ '^https://'
);

create table if not exists public.user_cover_choices (
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id text not null,
  variant_key text not null,
  label text not null default 'Capa variante',
  cover_url text not null check (cover_url ~ '^https://static[.]dc[.]com/'),
  updated_at timestamptz not null default now(),
  primary key (user_id, item_id)
);
alter table public.user_cover_choices drop constraint if exists user_cover_choices_cover_url_check;
alter table public.user_cover_choices add constraint user_cover_choices_cover_url_check check (
  cover_url ~ '^https://'
);
create index if not exists user_cover_choices_item_idx on public.user_cover_choices(item_id);

create table if not exists public.user_cover_styles (
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id text not null,
  style text not null default 'normal' check (style in ('normal', 'grayscale', 'gold')),
  updated_at timestamptz not null default now(),
  primary key (user_id, item_id)
);
create index if not exists user_cover_styles_item_idx on public.user_cover_styles(item_id);

create table if not exists public.user_series_cover_choices (
  user_id uuid not null references public.profiles(id) on delete cascade,
  series_id text not null,
  item_id text not null,
  cover_url text not null check (cover_url ~ '^https://'),
  variant_key text,
  is_variant boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, series_id)
);
create index if not exists user_series_cover_choices_series_idx on public.user_series_cover_choices(series_id);

create or replace function public.validate_user_cover_choice()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if not exists (
    select 1 from public.comic_cover_variants variant
    where variant.item_id = new.item_id
      and variant.variant_key = new.variant_key
      and variant.cover_url = new.cover_url
  ) then
    raise exception 'Capa variante não cadastrada para esta edição';
  end if;
  return new;
end;
$$;

drop trigger if exists validate_user_cover_choice_trigger on public.user_cover_choices;
create trigger validate_user_cover_choice_trigger
before insert or update on public.user_cover_choices
for each row execute procedure public.validate_user_cover_choice();

create table if not exists public.comic_likes (
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, item_id)
);

create table if not exists public.reading_progress (
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id text not null,
  page integer not null default 1 check (page > 0),
  total_pages integer not null default 1 check (total_pages > 0),
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, item_id)
);

create table if not exists public.comic_read_counts (
  item_id text primary key,
  clicks bigint not null default 0 check (clicks >= 0),
  updated_at timestamptz not null default now()
);
create index if not exists comic_read_counts_clicks_idx on public.comic_read_counts(clicks desc);

create table if not exists public.shelf_collection_likes (
  owner_id uuid not null references public.profiles(id) on delete cascade,
  collection_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (owner_id, collection_id, user_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id text not null,
  parent_id bigint references public.comments(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);
alter table public.comments add column if not exists parent_id bigint references public.comments(id) on delete cascade;

create table if not exists public.comment_likes (
  user_id uuid not null references public.profiles(id) on delete cascade,
  comment_id bigint not null references public.comments(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, comment_id)
);

create table if not exists public.moderation_actions (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  target_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  duration_until timestamptz,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  achievement_key text unique,
  name text not null,
  description text,
  icon text default '★'
);
alter table public.achievements add column if not exists achievement_key text;
drop index if exists public.achievements_key_unique;
create unique index if not exists achievements_key_unique on public.achievements(achievement_key);

create table if not exists public.user_achievements (
  user_id uuid not null references public.profiles(id) on delete cascade,
  achievement_id bigint not null references public.achievements(id) on delete cascade,
  awarded_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  primary key (user_id, achievement_id)
);

create or replace function public.notify_new_follow()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.create_notification(NEW.following_id, 'follow', 'Novo seguidor', 'Alguém começou a seguir você.', NEW.follower_id, null, '{}'::jsonb);
  return NEW;
end;
$$;

drop trigger if exists notify_new_follow_trigger on public.profile_follows;
create trigger notify_new_follow_trigger after insert on public.profile_follows for each row execute procedure public.notify_new_follow();

create or replace function public.notify_new_chat_message()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  v_preview text := regexp_replace(trim(NEW.body), '\s+', ' ', 'g');
begin
  if NEW.room_id is not null then return NEW; end if;
  if char_length(v_preview) > 300 then
    v_preview := left(v_preview, 297) || '...';
  end if;
  perform public.create_notification(NEW.recipient_id, 'message', 'Nova mensagem privada', 'Você recebeu uma nova mensagem privada: "' || v_preview || '"', NEW.sender_id, null, '{}'::jsonb);
  return NEW;
end;
$$;

create or replace function public.can_access_chat_room(p_room_id text)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1
    from public.chat_rooms room
    left join public.profiles profile on profile.id = auth.uid()
    where room.id = p_room_id
      and (
        room.access = 'public'
        or (room.access = 'premium' and profile.plan in ('premium', 'admin'))
        or (room.access = 'staff' and profile.plan in ('moderator', 'admin'))
      )
  )
$$;

create or replace function public.notify_chat_mentions()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  v_mentioned record;
  v_mentioned_id uuid;
begin
  for v_mentioned in select distinct lower((regexp_matches(NEW.body, '@([A-Za-z0-9_]{3,24})', 'gi'))[1]) as username loop
    select id into v_mentioned_id from public.profiles where lower(username) = v_mentioned.username limit 1;
    if v_mentioned_id is not null and v_mentioned_id <> NEW.sender_id and exists (select 1 from public.profiles where id = v_mentioned_id and allow_mentions) then
      perform public.create_notification(
        v_mentioned_id,
        'chat_mention',
        'Você foi mencionado no chat',
        'Alguém mencionou você em uma conversa.',
        NEW.sender_id,
        null,
        jsonb_build_object('room_id', NEW.room_id, 'message_id', NEW.id)
      );
    end if;
    v_mentioned_id := null;
  end loop;
  return NEW;
end;
$$;

drop trigger if exists notify_chat_mentions_trigger on public.chat_messages;
create trigger notify_chat_mentions_trigger after insert on public.chat_messages for each row execute procedure public.notify_chat_mentions();

drop trigger if exists notify_new_chat_message_trigger on public.chat_messages;
create trigger notify_new_chat_message_trigger after insert on public.chat_messages for each row execute procedure public.notify_new_chat_message();

create or replace function public.notify_collection_like()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  v_name text;
begin
  select name into v_name from public.shelf_collections where id = NEW.collection_id and owner_id = NEW.owner_id;
  perform public.create_notification(NEW.owner_id, 'collection_like', 'Coleção curtida', 'Sua coleção "' || coalesce(v_name, 'sem nome') || '" recebeu uma curtida.', NEW.user_id, null, jsonb_build_object('collection_id', NEW.collection_id));
  return NEW;
end;
$$;

drop trigger if exists notify_collection_like_trigger on public.shelf_collection_likes;
create trigger notify_collection_like_trigger after insert on public.shelf_collection_likes for each row execute procedure public.notify_collection_like();

create or replace function public.notify_comment_activity()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  v_parent_author uuid;
  v_mentioned_id uuid;
  v_mentioned record;
begin
  if NEW.parent_id is not null then
    select user_id into v_parent_author from public.comments where id = NEW.parent_id;
    perform public.create_notification(v_parent_author, 'comment_reply', 'Nova resposta ao seu comentário', 'Alguém respondeu a um comentário seu.', NEW.user_id, null, jsonb_build_object('item_id', NEW.item_id, 'comment_id', NEW.id));
  end if;
  for v_mentioned in select distinct lower((regexp_matches(NEW.body, '@([A-Za-z0-9_]{3,24})', 'gi'))[1]) as username loop
    select id into v_mentioned_id from public.profiles where lower(username) = v_mentioned.username limit 1;
    if v_mentioned_id is not null and exists (select 1 from public.profiles where id = v_mentioned_id and allow_mentions) then
      perform public.create_notification(v_mentioned_id, 'mention', 'Você foi mencionado', 'Alguém mencionou você em um comentário.', NEW.user_id, null, jsonb_build_object('item_id', NEW.item_id, 'comment_id', NEW.id));
    end if;
    v_mentioned_id := null;
  end loop;
  return NEW;
end;
$$;

drop trigger if exists notify_comment_activity_trigger on public.comments;
create trigger notify_comment_activity_trigger after insert on public.comments for each row execute procedure public.notify_comment_activity();

create or replace function public.notify_comment_like()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  v_comment record;
  v_body text;
begin
  select user_id, item_id, parent_id into v_comment
  from public.comments
  where id = NEW.comment_id;
  v_body := case when v_comment.parent_id is null
    then 'Alguém curtiu seu comentário.'
    else 'Alguém curtiu sua resposta.'
  end;
  perform public.create_notification(v_comment.user_id, 'comment_like', 'Comentário curtido', v_body, NEW.user_id, null, jsonb_build_object('comment_id', NEW.comment_id, 'item_id', v_comment.item_id));
  return NEW;
end;
$$;

drop trigger if exists notify_comment_like_trigger on public.comment_likes;
create trigger notify_comment_like_trigger after insert on public.comment_likes for each row execute procedure public.notify_comment_like();

create or replace function public.notify_blog_comment_activity()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  v_blog_author uuid;
  v_parent_author uuid;
  v_mentioned record;
  v_mentioned_id uuid;
  v_href text := '?pagina=blogs&blog=' || NEW.blog_id::text;
begin
  select author_id into v_blog_author from public.blog_posts where id = NEW.blog_id;
  if NEW.parent_id is not null then
    select user_id into v_parent_author from public.blog_comments where id = NEW.parent_id;
    perform public.create_notification(v_parent_author, 'comment_reply', 'Nova resposta no blog', 'Alguém respondeu ao seu comentário em um blog.', NEW.user_id, v_href, jsonb_build_object('blog_id', NEW.blog_id, 'comment_id', NEW.id));
  else
    perform public.create_notification(v_blog_author, 'comment_reply', 'Novo comentário no seu blog', 'Alguém comentou em uma publicação sua.', NEW.user_id, v_href, jsonb_build_object('blog_id', NEW.blog_id, 'comment_id', NEW.id));
  end if;
  for v_mentioned in select distinct lower((regexp_matches(NEW.body, '@([A-Za-z0-9_]{3,24})', 'gi'))[1]) as username loop
    select id into v_mentioned_id from public.profiles where lower(username) = v_mentioned.username limit 1;
    if v_mentioned_id is not null and exists (select 1 from public.profiles where id = v_mentioned_id and allow_mentions) then
      perform public.create_notification(v_mentioned_id, 'mention', 'Você foi mencionado em um comentário de blog', 'Alguém mencionou você em um comentário.', NEW.user_id, v_href, jsonb_build_object('blog_id', NEW.blog_id, 'comment_id', NEW.id));
    end if;
    v_mentioned_id := null;
  end loop;
  return NEW;
end;
$$;

drop trigger if exists notify_blog_comment_activity_trigger on public.blog_comments;
create trigger notify_blog_comment_activity_trigger after insert on public.blog_comments for each row execute procedure public.notify_blog_comment_activity();

create or replace function public.notify_blog_comment_like()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  v_comment record;
begin
  select user_id, blog_id into v_comment from public.blog_comments where id = NEW.blog_comment_id;
  perform public.create_notification(v_comment.user_id, 'comment_like', 'Comentário de blog curtido', 'Alguém curtiu seu comentário em um blog.', NEW.user_id, '?pagina=blogs&blog=' || v_comment.blog_id::text, jsonb_build_object('blog_id', v_comment.blog_id, 'comment_id', NEW.blog_comment_id));
  return NEW;
end;
$$;

drop trigger if exists notify_blog_comment_like_trigger on public.blog_comment_likes;
create trigger notify_blog_comment_like_trigger after insert on public.blog_comment_likes for each row execute procedure public.notify_blog_comment_like();

create or replace function public.notify_moderation_action()
returns trigger language plpgsql security definer set search_path = public
as $$
declare v_title text; v_body text;
begin
  v_title := case NEW.action when 'title' then 'Seu título foi atualizado' when 'silence' then 'Você foi silenciado' when 'unsilence' then 'Seu silêncio foi removido' when 'ban' then 'Sua conta foi suspensa' when 'unban' then 'Sua conta foi reativada' when 'hide' then 'Seu perfil foi ocultado' when 'unhide' then 'Seu perfil voltou a ficar visível' else 'Atualização de moderação' end;
  v_body := case NEW.action when 'title' then 'A equipe atualizou o título do seu perfil.' when 'silence' then 'Você não poderá comentar até o fim do período aplicado.' when 'unsilence' then 'Você pode comentar novamente.' else 'Uma ação de moderação foi aplicada à sua conta.' end;
  perform public.create_notification(NEW.target_id, 'moderation', v_title, v_body, NEW.actor_id, null, jsonb_build_object('action', NEW.action));
  return NEW;
end;
$$;

drop trigger if exists notify_moderation_action_trigger on public.moderation_actions;
create trigger notify_moderation_action_trigger after insert on public.moderation_actions for each row execute procedure public.notify_moderation_action();

insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('publisher-covers', 'publisher-covers', true) on conflict (id) do nothing;
drop policy if exists "publisher covers are public" on storage.objects;
drop policy if exists "moderators upload publisher covers" on storage.objects;
drop policy if exists "moderators update publisher covers" on storage.objects;
drop policy if exists "avatars are public" on storage.objects;
drop policy if exists "blog images are public" on storage.objects;
drop policy if exists "users upload blog images" on storage.objects;
drop policy if exists "users update own blog images" on storage.objects;
drop policy if exists "users delete own blog images" on storage.objects;
drop policy if exists "users upload own avatar" on storage.objects;
drop policy if exists "users update own avatar" on storage.objects;
create policy "avatars are public" on storage.objects for select using (bucket_id = 'avatars');
create policy "blog images are public" on storage.objects for select using (bucket_id = 'blog-images');
create policy "users upload blog images" on storage.objects for insert with check (bucket_id = 'blog-images' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "users update own blog images" on storage.objects for update using (bucket_id = 'blog-images' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "users delete own blog images" on storage.objects for delete using (bucket_id = 'blog-images' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "users upload own avatar" on storage.objects for insert with check (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "users update own avatar" on storage.objects for update using (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and plan = 'admin') $$;

create or replace function public.is_moderator()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and plan in ('moderator', 'admin')) $$;

create or replace function public.can_comment()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and not is_banned and (silenced_until is null or silenced_until <= now())) $$;

create or replace function public.can_customize_covers()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and plan in ('premium', 'moderator', 'admin')) $$;

create or replace function public.can_apply_cover_style(p_style text)
returns boolean language sql stable security definer set search_path = public
as $$
  select auth.uid() is not null
    and (
      p_style = 'grayscale'
      or exists (select 1 from public.profiles where id = auth.uid() and plan in ('premium', 'moderator', 'admin'))
    )
$$;

create policy "publisher covers are public" on storage.objects for select using (bucket_id = 'publisher-covers');
create policy "moderators upload publisher covers" on storage.objects for insert with check (bucket_id = 'publisher-covers' and public.is_moderator() and auth.uid()::text = (storage.foldername(name))[1]);
create policy "moderators update publisher covers" on storage.objects for update using (bucket_id = 'publisher-covers' and public.is_moderator() and auth.uid()::text = (storage.foldername(name))[1]);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, account_email)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8)), new.email);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.get_login_email(p_username text)
returns text language sql security definer set search_path = public
as $$ select account_email from public.profiles where lower(username) = lower(p_username) limit 1 $$;
grant execute on function public.get_login_email(text) to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.publisher_settings enable row level security;
alter table public.blog_posts enable row level security;
alter table public.blog_likes enable row level security;
alter table public.blog_comments enable row level security;
alter table public.blog_comment_likes enable row level security;
alter table public.blog_saves enable row level security;
alter table public.profile_follows enable row level security;
alter table public.notifications enable row level security;
alter table public.chat_messages enable row level security;
alter table public.chat_rooms enable row level security;
alter table public.favorites enable row level security;
alter table public.comic_cover_variants enable row level security;
alter table public.user_cover_choices enable row level security;
alter table public.user_cover_styles enable row level security;
alter table public.user_series_cover_choices enable row level security;
alter table public.comic_likes enable row level security;
alter table public.reading_progress enable row level security;
alter table public.comic_read_counts enable row level security;
alter table public.shelf_collections enable row level security;
alter table public.shelf_collection_likes enable row level security;
alter table public.comments enable row level security;
alter table public.comment_likes enable row level security;
alter table public.moderation_actions enable row level security;
alter table public.achievements enable row level security;
alter table public.user_achievements enable row level security;
alter table public.profile_xp_events enable row level security;

drop policy if exists "profiles are public" on public.profiles;
drop policy if exists "publisher settings are public" on public.publisher_settings;
drop policy if exists "moderators manage publisher settings" on public.publisher_settings;
drop policy if exists "published blogs are public" on public.blog_posts;
drop policy if exists "authors manage own blogs" on public.blog_posts;
drop policy if exists "moderators manage blogs" on public.blog_posts;
drop policy if exists "blog likes are public" on public.blog_likes;
drop policy if exists "users manage own blog likes" on public.blog_likes;
drop policy if exists "blog comments are public" on public.blog_comments;
drop policy if exists "users create blog comments" on public.blog_comments;
drop policy if exists "users delete own blog comments" on public.blog_comments;
drop policy if exists "blog comment likes are public" on public.blog_comment_likes;
drop policy if exists "users manage blog comment likes" on public.blog_comment_likes;
drop policy if exists "blog saves are visible" on public.blog_saves;
drop policy if exists "users manage own blog saves" on public.blog_saves;
drop policy if exists "profile follows are public" on public.profile_follows;
drop policy if exists "users manage own follows" on public.profile_follows;
drop policy if exists "users read own notifications" on public.notifications;
drop policy if exists "users update own notifications" on public.notifications;
drop policy if exists "admins insert notifications" on public.notifications;
drop policy if exists "participants read chat messages" on public.chat_messages;
drop policy if exists "users send chat messages" on public.chat_messages;
drop policy if exists "participants delete chat messages" on public.chat_messages;
drop policy if exists "chat rooms are visible to members" on public.chat_rooms;
drop policy if exists "users update own profile" on public.profiles;
drop policy if exists "users read own favorites" on public.favorites;
drop policy if exists "favorites are public" on public.favorites;
drop policy if exists "users manage own favorites" on public.favorites;
drop policy if exists "cover variants are public" on public.comic_cover_variants;
drop policy if exists "admins manage cover variants" on public.comic_cover_variants;
drop policy if exists "cover choices are public" on public.user_cover_choices;
drop policy if exists "premium users manage own cover choices" on public.user_cover_choices;
drop policy if exists "cover styles are public" on public.user_cover_styles;
drop policy if exists "premium users manage own cover styles" on public.user_cover_styles;
drop policy if exists "users manage own cover styles" on public.user_cover_styles;
drop policy if exists "series cover choices are public" on public.user_series_cover_choices;
drop policy if exists "users manage own series cover choices" on public.user_series_cover_choices;
drop policy if exists "comic likes are public" on public.comic_likes;
drop policy if exists "users manage own comic likes" on public.comic_likes;
drop policy if exists "reading progress is public" on public.reading_progress;
drop policy if exists "users manage own reading progress" on public.reading_progress;
drop policy if exists "comic read counts are public" on public.comic_read_counts;
drop policy if exists "public collections are visible" on public.shelf_collections;
drop policy if exists "owners manage collections" on public.shelf_collections;
drop policy if exists "moderators feature collections" on public.shelf_collections;
drop policy if exists "admins delete public collections" on public.shelf_collections;
drop policy if exists "collection likes are public" on public.shelf_collection_likes;
drop policy if exists "users manage collection likes" on public.shelf_collection_likes;
drop policy if exists "comments are public" on public.comments;
drop policy if exists "users create own comments" on public.comments;
drop policy if exists "users delete own comments" on public.comments;
drop policy if exists "comment likes are public" on public.comment_likes;
drop policy if exists "users manage comment likes" on public.comment_likes;
drop policy if exists "moderation history visible to moderators" on public.moderation_actions;
drop policy if exists "moderators create moderation history" on public.moderation_actions;
drop policy if exists "achievements are public" on public.achievements;
drop policy if exists "user achievements are public" on public.user_achievements;
drop policy if exists "admins manage achievements" on public.achievements;
drop policy if exists "admins award achievements" on public.user_achievements;

create policy "profiles are public" on public.profiles for select using (not profile_hidden or auth.uid() = id or public.is_moderator());
create policy "publisher settings are public" on public.publisher_settings for select using (true);
create policy "moderators manage publisher settings" on public.publisher_settings for all using (public.is_moderator()) with check (public.is_moderator());
create policy "published blogs are public" on public.blog_posts for select using (status = 'published' or auth.uid() = author_id or public.is_moderator());
create policy "authors manage own blogs" on public.blog_posts for all using (auth.uid() = author_id) with check (auth.uid() = author_id and is_featured = false);
create policy "moderators manage blogs" on public.blog_posts for all using (public.is_moderator()) with check (public.is_moderator());
create policy "blog likes are public" on public.blog_likes for select using (true);
create policy "users manage own blog likes" on public.blog_likes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "blog comments are public" on public.blog_comments for select using (true);
create policy "users create blog comments" on public.blog_comments for insert with check (auth.uid() = user_id and public.can_comment());
create policy "users delete own blog comments" on public.blog_comments for delete using (auth.uid() = user_id or public.is_moderator());
create policy "blog comment likes are public" on public.blog_comment_likes for select using (true);
create policy "users manage blog comment likes" on public.blog_comment_likes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "blog saves are visible" on public.blog_saves for select using (auth.uid() = user_id or exists (select 1 from public.profiles where id = user_id and shelf_blogs_public));
create policy "users manage own blog saves" on public.blog_saves for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "profile follows are public" on public.profile_follows for select using (true);
create policy "users manage own follows" on public.profile_follows for all using (auth.uid() = follower_id) with check (auth.uid() = follower_id and follower_id <> following_id);
create policy "users read own notifications" on public.notifications for select using (auth.uid() = user_id);
create policy "users update own notifications" on public.notifications for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "admins insert notifications" on public.notifications for insert with check (public.is_admin());
create policy "chat rooms are visible to members" on public.chat_rooms for select using (public.can_access_chat_room(id));
create policy "participants read chat messages" on public.chat_messages for select using (
  expires_at > now() and (
    (room_id is null and (auth.uid() = sender_id or auth.uid() = recipient_id))
    or (room_id is not null and public.can_access_chat_room(room_id))
  )
);
create policy "users send chat messages" on public.chat_messages for insert with check (
  auth.uid() = sender_id
  and expires_at <= now() + interval '24 hours'
  and expires_at > now()
  and (
    (room_id is null and recipient_id is not null and auth.uid() <> recipient_id and exists (select 1 from public.profiles where id = recipient_id and allow_messages))
    or (room_id is not null and recipient_id is null and public.can_access_chat_room(room_id))
  )
);
create policy "participants delete chat messages" on public.chat_messages for delete using (auth.uid() = sender_id or auth.uid() = recipient_id);
create policy "users update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "admins update user plans" on public.profiles;
create policy "admins update user plans" on public.profiles for update using (public.is_admin()) with check (public.is_admin());
create policy "favorites are public" on public.favorites for select using (
  auth.uid() = user_id or exists (select 1 from public.profiles where id = user_id and likes_public)
);
create policy "users manage own favorites" on public.favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "cover variants are public" on public.comic_cover_variants for select using (true);
create policy "admins manage cover variants" on public.comic_cover_variants for all using (public.is_admin()) with check (public.is_admin());
create policy "cover choices are public" on public.user_cover_choices for select using (true);
create policy "premium users manage own cover choices" on public.user_cover_choices for all using (auth.uid() = user_id and public.can_customize_covers()) with check (auth.uid() = user_id and public.can_customize_covers());
create policy "cover styles are public" on public.user_cover_styles for select using (true);
create policy "users manage own cover styles" on public.user_cover_styles for all using (auth.uid() = user_id) with check (auth.uid() = user_id and public.can_apply_cover_style(style));
create policy "series cover choices are public" on public.user_series_cover_choices for select using (true);
create policy "users manage own series cover choices" on public.user_series_cover_choices for all using (auth.uid() = user_id) with check (auth.uid() = user_id and (not is_variant or public.can_customize_covers()));
create policy "comic likes are public" on public.comic_likes for select using (
  auth.uid() = user_id or exists (select 1 from public.profiles where id = user_id and likes_public)
);
create policy "users manage own comic likes" on public.comic_likes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "reading progress is public" on public.reading_progress for select using (true);
create policy "users manage own reading progress" on public.reading_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "comic read counts are public" on public.comic_read_counts for select using (true);

create or replace function public.increment_comic_read(p_item_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_clicks bigint;
begin
  if p_item_id is null or length(trim(p_item_id)) = 0 or length(p_item_id) > 200 then
    raise exception 'Invalid comic item id';
  end if;

  insert into public.comic_read_counts (item_id, clicks, updated_at)
  values (p_item_id, 1, now())
  on conflict (item_id) do update
    set clicks = public.comic_read_counts.clicks + 1,
        updated_at = now()
  returning clicks into v_clicks;

  return v_clicks;
end;
$$;
grant execute on function public.increment_comic_read(text) to anon, authenticated;
create policy "public collections are visible" on public.shelf_collections for select using (is_public or auth.uid() = owner_id);
create policy "owners manage collections" on public.shelf_collections for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
create policy "moderators feature collections" on public.shelf_collections for update using (public.is_moderator()) with check (public.is_moderator());
create policy "admins delete public collections" on public.shelf_collections for delete using (public.is_admin() and is_public);
create policy "collection likes are public" on public.shelf_collection_likes for select using (
  exists (
    select 1 from public.shelf_collections collection
    where collection.id = shelf_collection_likes.collection_id
      and collection.owner_id = shelf_collection_likes.owner_id
      and collection.is_public
  )
);
create policy "users manage collection likes" on public.shelf_collection_likes for all
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id and exists (
    select 1 from public.shelf_collections collection
    where collection.id = shelf_collection_likes.collection_id
      and collection.owner_id = shelf_collection_likes.owner_id
      and collection.is_public
  )
);
create policy "comments are public" on public.comments for select using (true);
create policy "users create own comments" on public.comments for insert with check (auth.uid() = user_id and public.can_comment());
create policy "users delete own comments" on public.comments for delete using (auth.uid() = user_id or public.is_moderator());
create policy "comment likes are public" on public.comment_likes for select using (true);
create policy "users manage comment likes" on public.comment_likes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "moderation history visible to moderators" on public.moderation_actions for select using (public.is_moderator());
create policy "moderators create moderation history" on public.moderation_actions for insert with check (public.is_moderator() and auth.uid() = actor_id);
create policy "achievements are public" on public.achievements for select using (true);
create policy "user achievements are public" on public.user_achievements for select using (true);
create policy "admins manage achievements" on public.achievements for all using (public.is_admin()) with check (public.is_admin());
create policy "admins award achievements" on public.user_achievements for all using (public.is_admin()) with check (public.is_admin());

create or replace function public.send_notification_to_all(p_title text, p_body text, p_type text default 'announcement')
returns integer language plpgsql security definer set search_path = public
as $$
declare v_count integer;
begin
  if not public.is_admin() then raise exception 'Apenas administradores podem enviar notificações globais'; end if;
  insert into public.notifications(user_id, type, title, body, metadata)
  select id, p_type, left(trim(p_title), 120), left(trim(p_body), 500), jsonb_build_object('broadcast', true)
  from public.profiles
  where trim(p_title) <> '' and trim(p_body) <> '';
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
grant execute on function public.send_notification_to_all(text, text, text) to authenticated;

-- Atualiza a atividade; a exclusão definitiva da conta auth deve ser feita por Edge Function com secret key.
create or replace function public.profile_level_for_xp(p_xp integer)
returns integer language sql immutable as $$
  select greatest(1, floor(sqrt(greatest(coalesce(p_xp, 0), 0)::numeric / 100))::integer + 1)
$$;

create or replace function public.grant_profile_xp(p_event_type text, p_event_key text default null)
returns integer language plpgsql security definer set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_xp integer;
  v_key text;
  v_total integer;
begin
  if v_user_id is null or not exists (select 1 from public.profiles where id = v_user_id) then return 0; end if;
  v_xp := case p_event_type
    when 'read' then 10
    when 'comment' then 5
    when 'like' then 2
    when 'chat' then 3
    when 'blog' then 8
    when 'follow' then 2
    else 0
  end;
  if v_xp <= 0 then return 0; end if;
  v_key := coalesce(nullif(trim(p_event_key), ''), p_event_type || ':' || clock_timestamp()::text);
  insert into public.profile_xp_events(user_id, event_type, event_key, xp)
  values (v_user_id, p_event_type, v_key, v_xp)
  on conflict (user_id, event_key) do nothing;
  if not found then
    select xp into v_total from public.profiles where id = v_user_id;
    return coalesce(v_total, 0);
  end if;
  update public.profiles
  set xp = xp + v_xp,
      level = public.profile_level_for_xp(xp + v_xp)
  where id = v_user_id
  returning xp into v_total;
  return coalesce(v_total, 0);
end;
$$;
grant execute on function public.grant_profile_xp(text, text) to authenticated;

create or replace function public.daily_profile_checkin()
returns table(awarded_xp integer, streak integer, total_xp integer, current_level integer)
language plpgsql security definer set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_streak integer;
  v_award integer;
  v_inserted boolean := false;
begin
  if v_user_id is null then return; end if;
  select * into v_profile from public.profiles where id = v_user_id;
  if not found then return; end if;
  if v_profile.last_checkin_at is not null and v_profile.last_checkin_at::date = current_date then
    awarded_xp := 0; streak := coalesce(v_profile.daily_streak, 0); total_xp := v_profile.xp; current_level := v_profile.level; return next; return;
  end if;
  v_streak := case
    when v_profile.last_checkin_at is not null and v_profile.last_checkin_at::date = current_date - 1 then coalesce(v_profile.daily_streak, 0) + 1
    else 1
  end;
  v_award := 20 + least(v_streak * 5, 30);
  insert into public.profile_xp_events(user_id, event_type, event_key, xp)
  values (v_user_id, 'checkin', 'checkin:' || current_date::text, v_award)
  on conflict (user_id, event_key) do nothing;
  v_inserted := found;
  if v_inserted then
    update public.profiles
    set xp = xp + v_award,
        level = public.profile_level_for_xp(xp + v_award),
        daily_streak = v_streak,
        last_checkin_at = now()
    where id = v_user_id
    returning xp, level into total_xp, current_level;
  else
    select xp, level into total_xp, current_level from public.profiles where id = v_user_id;
  end if;
  awarded_xp := case when v_inserted then v_award else 0 end;
  streak := v_streak;
  return next;
end;
$$;
grant execute on function public.daily_profile_checkin() to authenticated;

create or replace function public.protect_profile_progress()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if current_user not in ('postgres', 'service_role') then
    new.xp := old.xp;
    new.level := old.level;
    new.daily_streak := old.daily_streak;
    new.last_checkin_at := old.last_checkin_at;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_progress_trigger on public.profiles;
create trigger protect_profile_progress_trigger
before update on public.profiles
for each row execute procedure public.protect_profile_progress();

create or replace function public.get_profile_ranking(p_period text default 'week', p_limit integer default 100)
returns table(
  user_id uuid,
  username text,
  avatar_url text,
  title text,
  title_color text,
  plan text,
  xp integer,
  level integer,
  last_seen_at timestamptz,
  period_xp bigint,
  ranking bigint,
  is_online boolean
)
language sql stable security definer set search_path = public
as $$
  with bounds as (
    select case lower(coalesce(p_period, 'week'))
      when 'day' then now() - interval '24 hours'
      when 'all' then '-infinity'::timestamptz
      else now() - interval '7 days'
    end as since_at
  ),
  activity as (
    select events.user_id, sum(events.xp)::bigint as period_xp
    from public.profile_xp_events events, bounds
    where events.created_at >= bounds.since_at
    group by events.user_id
  ),
  members as (
    select profile.id as user_id, profile.username, profile.avatar_url, profile.title, profile.title_color,
      profile.plan, profile.xp, profile.level, profile.last_seen_at,
      coalesce(activity.period_xp, 0)::bigint as period_xp
    from public.profiles profile
    left join activity on activity.user_id = profile.id
    where not profile.profile_hidden
  )
  select members.user_id, members.username, members.avatar_url, members.title, members.title_color,
    members.plan, members.xp, members.level, members.last_seen_at, members.period_xp,
    case when members.plan in ('free', 'premium') then rank() over (
      order by case when members.plan in ('free', 'premium') then members.period_xp end desc nulls last,
        case when members.plan in ('free', 'premium') then members.xp end desc nulls last,
        case when members.plan in ('free', 'premium') then members.username end asc
    ) end as ranking,
    members.last_seen_at >= now() - interval '5 minutes' as is_online
  from members
  order by members.period_xp desc, members.xp desc, members.username asc
  limit greatest(1, least(coalesce(p_limit, 100), 500));
$$;
grant execute on function public.get_profile_ranking(text, integer) to anon, authenticated;

create or replace function public.touch_profile()
returns void language sql security invoker as $$ update public.profiles set last_seen_at = now() where id = auth.uid(); $$;

insert into public.achievements (achievement_key, name, description, icon) values
  ('first_read', 'Primeira leitura', 'Abriu seu primeiro quadrinho.', '📖'),
  ('first_completed', 'Primeira conclusão', 'Concluiu todas as edições de uma série.', '🏁'),
  ('first_favorite', 'Primeiro favorito', 'Salvou sua primeira edição na estante.', '★'),
  ('first_comment', 'Voz da banca', 'Publicou seu primeiro comentário.', '💬'),
  ('five_completed', 'Maratona', 'Concluiu cinco séries.', '🏆')
on conflict (achievement_key) do update set name = excluded.name, description = excluded.description, icon = excluded.icon;

create or replace function public.award_achievement(p_key text)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_achievement_id bigint;
  v_inserted_achievement bigint;
  v_allowed boolean := false;
begin
  select id into v_achievement_id from public.achievements where achievement_key = p_key;
  if v_achievement_id is null or auth.uid() is null then return; end if;
  v_allowed := case p_key
    when 'first_read' then exists (select 1 from public.reading_progress where user_id = auth.uid())
    when 'first_completed' then exists (select 1 from public.reading_progress where user_id = auth.uid() and completed)
    when 'first_favorite' then exists (select 1 from public.favorites where user_id = auth.uid())
    when 'first_comment' then exists (select 1 from public.comments where user_id = auth.uid())
    when 'five_completed' then (select count(*) >= 5 from public.reading_progress where user_id = auth.uid() and completed)
    else false
  end;
  if v_allowed then
    insert into public.user_achievements (user_id, achievement_id) values (auth.uid(), v_achievement_id) on conflict do nothing returning achievement_id into v_inserted_achievement;
    if v_inserted_achievement is not null then
      perform public.create_notification(auth.uid(), 'achievement', 'Nova conquista', 'Você desbloqueou uma nova conquista.', null, null, jsonb_build_object('achievement_id', v_achievement_id, 'achievement_key', p_key));
    end if;
  end if;
end;
$$;
grant execute on function public.award_achievement(text) to authenticated;

create or replace function public.set_user_plan(p_username text, p_plan text)
returns void language plpgsql security definer set search_path = public as $$
declare v_target public.profiles%rowtype;
begin
  if not public.is_moderator() then raise exception 'Apenas moderadores e administradores podem alterar planos'; end if;
  if p_plan not in ('free', 'premium', 'moderator') then raise exception 'Plano inválido'; end if;
  if p_plan = 'moderator' and not public.is_admin() then raise exception 'Apenas administradores podem promover moderadores'; end if;
  select * into v_target from public.profiles where lower(username) = lower(trim(p_username));
  if not found then raise exception 'Usuário não encontrado'; end if;
  update public.profiles set plan = p_plan where id = v_target.id;
  if v_target.plan is distinct from p_plan then
    perform public.create_notification(v_target.id, 'plan', 'Plano da conta atualizado', 'Seu plano mudou de ' || v_target.plan || ' para ' || p_plan || '.', auth.uid(), null, jsonb_build_object('old_plan', v_target.plan, 'new_plan', p_plan));
  end if;
end;
$$;
grant execute on function public.set_user_plan(text, text) to authenticated;

create or replace function public.moderate_user(p_username text, p_action text, p_duration text default null, p_title text default null, p_title_color text default null)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_target public.profiles%rowtype;
  v_until timestamptz := null;
begin
  if not public.is_moderator() then raise exception 'Apenas moderadores e administradores podem moderar'; end if;
  select * into v_target from public.profiles where lower(username) = lower(trim(p_username));
  if not found then raise exception 'Usuário não encontrado'; end if;
  if v_target.plan in ('moderator', 'admin') and not public.is_admin() then raise exception 'Moderadores não podem moderar moderadores'; end if;
  if p_action = 'silence' then
    v_until := case p_duration when '24h' then now() + interval '24 hours' when '3d' then now() + interval '3 days' when '1m' then now() + interval '1 month' else now() + interval '24 hours' end;
    update public.profiles set silenced_until = v_until where id = v_target.id;
  elsif p_action = 'unsilence' then update public.profiles set silenced_until = null where id = v_target.id;
  elsif p_action = 'ban' then update public.profiles set is_banned = true where id = v_target.id;
  elsif p_action = 'unban' then update public.profiles set is_banned = false where id = v_target.id;
  elsif p_action = 'hide' then update public.profiles set profile_hidden = true where id = v_target.id;
  elsif p_action = 'unhide' then update public.profiles set profile_hidden = false where id = v_target.id;
  elsif p_action = 'title' then update public.profiles set title = nullif(trim(p_title), ''), title_color = coalesce(nullif(p_title_color, ''), title_color) where id = v_target.id;
  else raise exception 'Ação de moderação inválida';
  end if;
  insert into public.moderation_actions(actor_id, target_id, action, duration_until, details)
  values (auth.uid(), v_target.id, p_action, v_until, jsonb_build_object('duration', p_duration, 'title', p_title));
end;
$$;
grant execute on function public.moderate_user(text, text, text, text, text) to authenticated;
